// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/access"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/predicate"
)

// AccessUpdate is the builder for updating Access entities.
type AccessUpdate struct {
	config
	hooks    []Hook
	mutation *AccessMutation
}

// Where appends a list predicates to the AccessUpdate builder.
func (_u *AccessUpdate) Where(ps ...predicate.Access) *AccessUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *AccessUpdate) SetCode(v string) *AccessUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *AccessUpdate) SetNillableCode(v *string) *AccessUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetExpiration sets the "expiration" field.
func (_u *AccessUpdate) SetExpiration(v time.Time) *AccessUpdate {
	_u.mutation.SetExpiration(v)
	return _u
}

// SetNillableExpiration sets the "expiration" field if the given value is not nil.
func (_u *AccessUpdate) SetNillableExpiration(v *time.Time) *AccessUpdate {
	if v != nil {
		_u.SetExpiration(*v)
	}
	return _u
}

// ClearExpiration clears the value of the "expiration" field.
func (_u *AccessUpdate) ClearExpiration() *AccessUpdate {
	_u.mutation.ClearExpiration()
	return _u
}

// SetIdent sets the "ident" field.
func (_u *AccessUpdate) SetIdent(v string) *AccessUpdate {
	_u.mutation.SetIdent(v)
	return _u
}

// SetNillableIdent sets the "ident" field if the given value is not nil.
func (_u *AccessUpdate) SetNillableIdent(v *string) *AccessUpdate {
	if v != nil {
		_u.SetIdent(*v)
	}
	return _u
}

// ClearIdent clears the value of the "ident" field.
func (_u *AccessUpdate) ClearIdent() *AccessUpdate {
	_u.mutation.ClearIdent()
	return _u
}

// SetLimit sets the "limit" field.
func (_u *AccessUpdate) SetLimit(v int) *AccessUpdate {
	_u.mutation.ResetLimit()
	_u.mutation.SetLimit(v)
	return _u
}

// SetNillableLimit sets the "limit" field if the given value is not nil.
func (_u *AccessUpdate) SetNillableLimit(v *int) *AccessUpdate {
	if v != nil {
		_u.SetLimit(*v)
	}
	return _u
}

// AddLimit adds value to the "limit" field.
func (_u *AccessUpdate) AddLimit(v int) *AccessUpdate {
	_u.mutation.AddLimit(v)
	return _u
}

// ClearLimit clears the value of the "limit" field.
func (_u *AccessUpdate) ClearLimit() *AccessUpdate {
	_u.mutation.ClearLimit()
	return _u
}

// SetOrder sets the "order" field.
func (_u *AccessUpdate) SetOrder(v int) *AccessUpdate {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *AccessUpdate) SetNillableOrder(v *int) *AccessUpdate {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *AccessUpdate) AddOrder(v int) *AccessUpdate {
	_u.mutation.AddOrder(v)
	return _u
}

// ClearOrder clears the value of the "order" field.
func (_u *AccessUpdate) ClearOrder() *AccessUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// SetSystems sets the "systems" field.
func (_u *AccessUpdate) SetSystems(v string) *AccessUpdate {
	_u.mutation.SetSystems(v)
	return _u
}

// SetNillableSystems sets the "systems" field if the given value is not nil.
func (_u *AccessUpdate) SetNillableSystems(v *string) *AccessUpdate {
	if v != nil {
		_u.SetSystems(*v)
	}
	return _u
}

// Mutation returns the AccessMutation object of the builder.
func (_u *AccessUpdate) Mutation() *AccessMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccessUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccessUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AccessUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(access.Table, access.Columns, sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(access.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Expiration(); ok {
		_spec.SetField(access.FieldExpiration, field.TypeTime, value)
	}
	if _u.mutation.ExpirationCleared() {
		_spec.ClearField(access.FieldExpiration, field.TypeTime)
	}
	if value, ok := _u.mutation.Ident(); ok {
		_spec.SetField(access.FieldIdent, field.TypeString, value)
	}
	if _u.mutation.IdentCleared() {
		_spec.ClearField(access.FieldIdent, field.TypeString)
	}
	if value, ok := _u.mutation.Limit(); ok {
		_spec.SetField(access.FieldLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLimit(); ok {
		_spec.AddField(access.FieldLimit, field.TypeInt, value)
	}
	if _u.mutation.LimitCleared() {
		_spec.ClearField(access.FieldLimit, field.TypeInt)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(access.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(access.FieldOrder, field.TypeInt, value)
	}
	if _u.mutation.OrderCleared() {
		_spec.ClearField(access.FieldOrder, field.TypeInt)
	}
	if value, ok := _u.mutation.Systems(); ok {
		_spec.SetField(access.FieldSystems, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{access.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccessUpdateOne is the builder for updating a single Access entity.
type AccessUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessMutation
}

// SetCode sets the "code" field.
func (_u *AccessUpdateOne) SetCode(v string) *AccessUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *AccessUpdateOne) SetNillableCode(v *string) *AccessUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetExpiration sets the "expiration" field.
func (_u *AccessUpdateOne) SetExpiration(v time.Time) *AccessUpdateOne {
	_u.mutation.SetExpiration(v)
	return _u
}

// SetNillableExpiration sets the "expiration" field if the given value is not nil.
func (_u *AccessUpdateOne) SetNillableExpiration(v *time.Time) *AccessUpdateOne {
	if v != nil {
		_u.SetExpiration(*v)
	}
	return _u
}

// ClearExpiration clears the value of the "expiration" field.
func (_u *AccessUpdateOne) ClearExpiration() *AccessUpdateOne {
	_u.mutation.ClearExpiration()
	return _u
}

// SetIdent sets the "ident" field.
func (_u *AccessUpdateOne) SetIdent(v string) *AccessUpdateOne {
	_u.mutation.SetIdent(v)
	return _u
}

// SetNillableIdent sets the "ident" field if the given value is not nil.
func (_u *AccessUpdateOne) SetNillableIdent(v *string) *AccessUpdateOne {
	if v != nil {
		_u.SetIdent(*v)
	}
	return _u
}

// ClearIdent clears the value of the "ident" field.
func (_u *AccessUpdateOne) ClearIdent() *AccessUpdateOne {
	_u.mutation.ClearIdent()
	return _u
}

// SetLimit sets the "limit" field.
func (_u *AccessUpdateOne) SetLimit(v int) *AccessUpdateOne {
	_u.mutation.ResetLimit()
	_u.mutation.SetLimit(v)
	return _u
}

// SetNillableLimit sets the "limit" field if the given value is not nil.
func (_u *AccessUpdateOne) SetNillableLimit(v *int) *AccessUpdateOne {
	if v != nil {
		_u.SetLimit(*v)
	}
	return _u
}

// AddLimit adds value to the "limit" field.
func (_u *AccessUpdateOne) AddLimit(v int) *AccessUpdateOne {
	_u.mutation.AddLimit(v)
	return _u
}

// ClearLimit clears the value of the "limit" field.
func (_u *AccessUpdateOne) ClearLimit() *AccessUpdateOne {
	_u.mutation.ClearLimit()
	return _u
}

// SetOrder sets the "order" field.
func (_u *AccessUpdateOne) SetOrder(v int) *AccessUpdateOne {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *AccessUpdateOne) SetNillableOrder(v *int) *AccessUpdateOne {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *AccessUpdateOne) AddOrder(v int) *AccessUpdateOne {
	_u.mutation.AddOrder(v)
	return _u
}

// ClearOrder clears the value of the "order" field.
func (_u *AccessUpdateOne) ClearOrder() *AccessUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// SetSystems sets the "systems" field.
func (_u *AccessUpdateOne) SetSystems(v string) *AccessUpdateOne {
	_u.mutation.SetSystems(v)
	return _u
}

// SetNillableSystems sets the "systems" field if the given value is not nil.
func (_u *AccessUpdateOne) SetNillableSystems(v *string) *AccessUpdateOne {
	if v != nil {
		_u.SetSystems(*v)
	}
	return _u
}

// Mutation returns the AccessMutation object of the builder.
func (_u *AccessUpdateOne) Mutation() *AccessMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccessUpdate builder.
func (_u *AccessUpdateOne) Where(ps ...predicate.Access) *AccessUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccessUpdateOne) Select(field string, fields ...string) *AccessUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Access entity.
func (_u *AccessUpdateOne) Save(ctx context.Context) (*Access, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessUpdateOne) SaveX(ctx context.Context) *Access {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccessUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AccessUpdateOne) sqlSave(ctx context.Context) (_node *Access, err error) {
	_spec := sqlgraph.NewUpdateSpec(access.Table, access.Columns, sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Access.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, access.FieldID)
		for _, f := range fields {
			if !access.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != access.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(access.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Expiration(); ok {
		_spec.SetField(access.FieldExpiration, field.TypeTime, value)
	}
	if _u.mutation.ExpirationCleared() {
		_spec.ClearField(access.FieldExpiration, field.TypeTime)
	}
	if value, ok := _u.mutation.Ident(); ok {
		_spec.SetField(access.FieldIdent, field.TypeString, value)
	}
	if _u.mutation.IdentCleared() {
		_spec.ClearField(access.FieldIdent, field.TypeString)
	}
	if value, ok := _u.mutation.Limit(); ok {
		_spec.SetField(access.FieldLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLimit(); ok {
		_spec.AddField(access.FieldLimit, field.TypeInt, value)
	}
	if _u.mutation.LimitCleared() {
		_spec.ClearField(access.FieldLimit, field.TypeInt)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(access.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(access.FieldOrder, field.TypeInt, value)
	}
	if _u.mutation.OrderCleared() {
		_spec.ClearField(access.FieldOrder, field.TypeInt)
	}
	if value, ok := _u.mutation.Systems(); ok {
		_spec.SetField(access.FieldSystems, field.TypeString, value)
	}
	_node = &Access{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{access.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
