// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/access"
)

// AccessCreate is the builder for creating a Access entity.
type AccessCreate struct {
	config
	mutation *AccessMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *AccessCreate) SetCode(v string) *AccessCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetExpiration sets the "expiration" field.
func (_c *AccessCreate) SetExpiration(v time.Time) *AccessCreate {
	_c.mutation.SetExpiration(v)
	return _c
}

// SetNillableExpiration sets the "expiration" field if the given value is not nil.
func (_c *AccessCreate) SetNillableExpiration(v *time.Time) *AccessCreate {
	if v != nil {
		_c.SetExpiration(*v)
	}
	return _c
}

// SetIdent sets the "ident" field.
func (_c *AccessCreate) SetIdent(v string) *AccessCreate {
	_c.mutation.SetIdent(v)
	return _c
}

// SetNillableIdent sets the "ident" field if the given value is not nil.
func (_c *AccessCreate) SetNillableIdent(v *string) *AccessCreate {
	if v != nil {
		_c.SetIdent(*v)
	}
	return _c
}

// SetLimit sets the "limit" field.
func (_c *AccessCreate) SetLimit(v int) *AccessCreate {
	_c.mutation.SetLimit(v)
	return _c
}

// SetNillableLimit sets the "limit" field if the given value is not nil.
func (_c *AccessCreate) SetNillableLimit(v *int) *AccessCreate {
	if v != nil {
		_c.SetLimit(*v)
	}
	return _c
}

// SetOrder sets the "order" field.
func (_c *AccessCreate) SetOrder(v int) *AccessCreate {
	_c.mutation.SetOrder(v)
	return _c
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_c *AccessCreate) SetNillableOrder(v *int) *AccessCreate {
	if v != nil {
		_c.SetOrder(*v)
	}
	return _c
}

// SetSystems sets the "systems" field.
func (_c *AccessCreate) SetSystems(v string) *AccessCreate {
	_c.mutation.SetSystems(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AccessCreate) SetID(v int) *AccessCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AccessMutation object of the builder.
func (_c *AccessCreate) Mutation() *AccessMutation {
	return _c.mutation
}

// Save creates the Access in the database.
func (_c *AccessCreate) Save(ctx context.Context) (*Access, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccessCreate) SaveX(ctx context.Context) *Access {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccessCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Access.code"`)}
	}
	if _, ok := _c.mutation.Systems(); !ok {
		return &ValidationError{Name: "systems", err: errors.New(`ent: missing required field "Access.systems"`)}
	}
	return nil
}

func (_c *AccessCreate) sqlSave(ctx context.Context) (*Access, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccessCreate) createSpec() (*Access, *sqlgraph.CreateSpec) {
	var (
		_node = &Access{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(access.Table, sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(access.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Expiration(); ok {
		_spec.SetField(access.FieldExpiration, field.TypeTime, value)
		_node.Expiration = &value
	}
	if value, ok := _c.mutation.Ident(); ok {
		_spec.SetField(access.FieldIdent, field.TypeString, value)
		_node.Ident = &value
	}
	if value, ok := _c.mutation.Limit(); ok {
		_spec.SetField(access.FieldLimit, field.TypeInt, value)
		_node.Limit = &value
	}
	if value, ok := _c.mutation.Order(); ok {
		_spec.SetField(access.FieldOrder, field.TypeInt, value)
		_node.Order = &value
	}
	if value, ok := _c.mutation.Systems(); ok {
		_spec.SetField(access.FieldSystems, field.TypeString, value)
		_node.Systems = value
	}
	return _node, _spec
}

// AccessCreateBulk is the builder for creating many Access entities in bulk.
type AccessCreateBulk struct {
	config
	err      error
	builders []*AccessCreate
}

// Save creates the Access entities in the database.
func (_c *AccessCreateBulk) Save(ctx context.Context) ([]*Access, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Access, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccessCreateBulk) SaveX(ctx context.Context) []*Access {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
