// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/apikey"
)

// Apikey is the model entity for the Apikey schema.
type Apikey struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Disabled holds the value of the "disabled" field.
	Disabled *bool `json:"disabled,omitempty"`
	// Ident holds the value of the "ident" field.
	Ident *string `json:"ident,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Order holds the value of the "order" field.
	Order *int `json:"order,omitempty"`
	// Systems holds the value of the "systems" field.
	Systems      string `json:"systems,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Apikey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apikey.FieldDisabled:
			values[i] = new(sql.NullBool)
		case apikey.FieldID, apikey.FieldOrder:
			values[i] = new(sql.NullInt64)
		case apikey.FieldIdent, apikey.FieldKey, apikey.FieldSystems:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Apikey fields.
func (_m *Apikey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apikey.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case apikey.FieldDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field disabled", values[i])
			} else if value.Valid {
				_m.Disabled = new(bool)
				*_m.Disabled = value.Bool
			}
		case apikey.FieldIdent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ident", values[i])
			} else if value.Valid {
				_m.Ident = new(string)
				*_m.Ident = value.String
			}
		case apikey.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case apikey.FieldOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order", values[i])
			} else if value.Valid {
				_m.Order = new(int)
				*_m.Order = int(value.Int64)
			}
		case apikey.FieldSystems:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field systems", values[i])
			} else if value.Valid {
				_m.Systems = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Apikey.
// This includes values selected through modifiers, order, etc.
func (_m *Apikey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Apikey.
// Note that you need to call Apikey.Unwrap() before calling this method if this Apikey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Apikey) Update() *ApikeyUpdateOne {
	return NewApikeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Apikey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Apikey) Unwrap() *Apikey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Apikey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Apikey) String() string {
	var builder strings.Builder
	builder.WriteString("Apikey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.Disabled; v != nil {
		builder.WriteString("disabled=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Ident; v != nil {
		builder.WriteString("ident=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	if v := _m.Order; v != nil {
		builder.WriteString("order=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("systems=")
	builder.WriteString(_m.Systems)
	builder.WriteByte(')')
	return builder.String()
}

// Apikeys is a parsable slice of Apikey.
type Apikeys []*Apikey
