// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/apikey"
)

// ApikeyCreate is the builder for creating a Apikey entity.
type ApikeyCreate struct {
	config
	mutation *ApikeyMutation
	hooks    []Hook
}

// SetDisabled sets the "disabled" field.
func (_c *ApikeyCreate) SetDisabled(v bool) *ApikeyCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *ApikeyCreate) SetNillableDisabled(v *bool) *ApikeyCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetIdent sets the "ident" field.
func (_c *ApikeyCreate) SetIdent(v string) *ApikeyCreate {
	_c.mutation.SetIdent(v)
	return _c
}

// SetNillableIdent sets the "ident" field if the given value is not nil.
func (_c *ApikeyCreate) SetNillableIdent(v *string) *ApikeyCreate {
	if v != nil {
		_c.SetIdent(*v)
	}
	return _c
}

// SetKey sets the "key" field.
func (_c *ApikeyCreate) SetKey(v string) *ApikeyCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetOrder sets the "order" field.
func (_c *ApikeyCreate) SetOrder(v int) *ApikeyCreate {
	_c.mutation.SetOrder(v)
	return _c
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_c *ApikeyCreate) SetNillableOrder(v *int) *ApikeyCreate {
	if v != nil {
		_c.SetOrder(*v)
	}
	return _c
}

// SetSystems sets the "systems" field.
func (_c *ApikeyCreate) SetSystems(v string) *ApikeyCreate {
	_c.mutation.SetSystems(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ApikeyCreate) SetID(v int) *ApikeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ApikeyMutation object of the builder.
func (_c *ApikeyCreate) Mutation() *ApikeyMutation {
	return _c.mutation
}

// Save creates the Apikey in the database.
func (_c *ApikeyCreate) Save(ctx context.Context) (*Apikey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ApikeyCreate) SaveX(ctx context.Context) *Apikey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApikeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApikeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ApikeyCreate) defaults() {
	if _, ok := _c.mutation.Disabled(); !ok {
		v := apikey.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ApikeyCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Apikey.key"`)}
	}
	if _, ok := _c.mutation.Systems(); !ok {
		return &ValidationError{Name: "systems", err: errors.New(`ent: missing required field "Apikey.systems"`)}
	}
	return nil
}

func (_c *ApikeyCreate) sqlSave(ctx context.Context) (*Apikey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ApikeyCreate) createSpec() (*Apikey, *sqlgraph.CreateSpec) {
	var (
		_node = &Apikey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apikey.Table, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(apikey.FieldDisabled, field.TypeBool, value)
		_node.Disabled = &value
	}
	if value, ok := _c.mutation.Ident(); ok {
		_spec.SetField(apikey.FieldIdent, field.TypeString, value)
		_node.Ident = &value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(apikey.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Order(); ok {
		_spec.SetField(apikey.FieldOrder, field.TypeInt, value)
		_node.Order = &value
	}
	if value, ok := _c.mutation.Systems(); ok {
		_spec.SetField(apikey.FieldSystems, field.TypeString, value)
		_node.Systems = value
	}
	return _node, _spec
}

// ApikeyCreateBulk is the builder for creating many Apikey entities in bulk.
type ApikeyCreateBulk struct {
	config
	err      error
	builders []*ApikeyCreate
}

// Save creates the Apikey entities in the database.
func (_c *ApikeyCreateBulk) Save(ctx context.Context) ([]*Apikey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Apikey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApikeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ApikeyCreateBulk) SaveX(ctx context.Context) []*Apikey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApikeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApikeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
