// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/call"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/predicate"
)

// CallUpdate is the builder for updating Call entities.
type CallUpdate struct {
	config
	hooks    []Hook
	mutation *CallMutation
}

// Where appends a list predicates to the CallUpdate builder.
func (_u *CallUpdate) Where(ps ...predicate.Call) *CallUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAudio sets the "audio" field.
func (_u *CallUpdate) SetAudio(v []byte) *CallUpdate {
	_u.mutation.SetAudio(v)
	return _u
}

// SetAudioName sets the "audio_name" field.
func (_u *CallUpdate) SetAudioName(v string) *CallUpdate {
	_u.mutation.SetAudioName(v)
	return _u
}

// SetNillableAudioName sets the "audio_name" field if the given value is not nil.
func (_u *CallUpdate) SetNillableAudioName(v *string) *CallUpdate {
	if v != nil {
		_u.SetAudioName(*v)
	}
	return _u
}

// ClearAudioName clears the value of the "audio_name" field.
func (_u *CallUpdate) ClearAudioName() *CallUpdate {
	_u.mutation.ClearAudioName()
	return _u
}

// SetAudioType sets the "audio_type" field.
func (_u *CallUpdate) SetAudioType(v string) *CallUpdate {
	_u.mutation.SetAudioType(v)
	return _u
}

// SetNillableAudioType sets the "audio_type" field if the given value is not nil.
func (_u *CallUpdate) SetNillableAudioType(v *string) *CallUpdate {
	if v != nil {
		_u.SetAudioType(*v)
	}
	return _u
}

// ClearAudioType clears the value of the "audio_type" field.
func (_u *CallUpdate) ClearAudioType() *CallUpdate {
	_u.mutation.ClearAudioType()
	return _u
}

// SetDateTime sets the "date_time" field.
func (_u *CallUpdate) SetDateTime(v time.Time) *CallUpdate {
	_u.mutation.SetDateTime(v)
	return _u
}

// SetNillableDateTime sets the "date_time" field if the given value is not nil.
func (_u *CallUpdate) SetNillableDateTime(v *time.Time) *CallUpdate {
	if v != nil {
		_u.SetDateTime(*v)
	}
	return _u
}

// SetFrequencies sets the "frequencies" field.
func (_u *CallUpdate) SetFrequencies(v string) *CallUpdate {
	_u.mutation.SetFrequencies(v)
	return _u
}

// SetNillableFrequencies sets the "frequencies" field if the given value is not nil.
func (_u *CallUpdate) SetNillableFrequencies(v *string) *CallUpdate {
	if v != nil {
		_u.SetFrequencies(*v)
	}
	return _u
}

// SetFrequency sets the "frequency" field.
func (_u *CallUpdate) SetFrequency(v int) *CallUpdate {
	_u.mutation.ResetFrequency()
	_u.mutation.SetFrequency(v)
	return _u
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_u *CallUpdate) SetNillableFrequency(v *int) *CallUpdate {
	if v != nil {
		_u.SetFrequency(*v)
	}
	return _u
}

// AddFrequency adds value to the "frequency" field.
func (_u *CallUpdate) AddFrequency(v int) *CallUpdate {
	_u.mutation.AddFrequency(v)
	return _u
}

// ClearFrequency clears the value of the "frequency" field.
func (_u *CallUpdate) ClearFrequency() *CallUpdate {
	_u.mutation.ClearFrequency()
	return _u
}

// SetPatches sets the "patches" field.
func (_u *CallUpdate) SetPatches(v string) *CallUpdate {
	_u.mutation.SetPatches(v)
	return _u
}

// SetNillablePatches sets the "patches" field if the given value is not nil.
func (_u *CallUpdate) SetNillablePatches(v *string) *CallUpdate {
	if v != nil {
		_u.SetPatches(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *CallUpdate) SetSource(v int) *CallUpdate {
	_u.mutation.ResetSource()
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *CallUpdate) SetNillableSource(v *int) *CallUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// AddSource adds value to the "source" field.
func (_u *CallUpdate) AddSource(v int) *CallUpdate {
	_u.mutation.AddSource(v)
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *CallUpdate) ClearSource() *CallUpdate {
	_u.mutation.ClearSource()
	return _u
}

// SetSources sets the "sources" field.
func (_u *CallUpdate) SetSources(v string) *CallUpdate {
	_u.mutation.SetSources(v)
	return _u
}

// SetNillableSources sets the "sources" field if the given value is not nil.
func (_u *CallUpdate) SetNillableSources(v *string) *CallUpdate {
	if v != nil {
		_u.SetSources(*v)
	}
	return _u
}

// SetSystem sets the "system" field.
func (_u *CallUpdate) SetSystem(v int) *CallUpdate {
	_u.mutation.ResetSystem()
	_u.mutation.SetSystem(v)
	return _u
}

// SetNillableSystem sets the "system" field if the given value is not nil.
func (_u *CallUpdate) SetNillableSystem(v *int) *CallUpdate {
	if v != nil {
		_u.SetSystem(*v)
	}
	return _u
}

// AddSystem adds value to the "system" field.
func (_u *CallUpdate) AddSystem(v int) *CallUpdate {
	_u.mutation.AddSystem(v)
	return _u
}

// SetTalkgroup sets the "talkgroup" field.
func (_u *CallUpdate) SetTalkgroup(v int) *CallUpdate {
	_u.mutation.ResetTalkgroup()
	_u.mutation.SetTalkgroup(v)
	return _u
}

// SetNillableTalkgroup sets the "talkgroup" field if the given value is not nil.
func (_u *CallUpdate) SetNillableTalkgroup(v *int) *CallUpdate {
	if v != nil {
		_u.SetTalkgroup(*v)
	}
	return _u
}

// AddTalkgroup adds value to the "talkgroup" field.
func (_u *CallUpdate) AddTalkgroup(v int) *CallUpdate {
	_u.mutation.AddTalkgroup(v)
	return _u
}

// Mutation returns the CallMutation object of the builder.
func (_u *CallUpdate) Mutation() *CallMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CallUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CallUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CallUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CallUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CallUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(call.Table, call.Columns, sqlgraph.NewFieldSpec(call.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Audio(); ok {
		_spec.SetField(call.FieldAudio, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.AudioName(); ok {
		_spec.SetField(call.FieldAudioName, field.TypeString, value)
	}
	if _u.mutation.AudioNameCleared() {
		_spec.ClearField(call.FieldAudioName, field.TypeString)
	}
	if value, ok := _u.mutation.AudioType(); ok {
		_spec.SetField(call.FieldAudioType, field.TypeString, value)
	}
	if _u.mutation.AudioTypeCleared() {
		_spec.ClearField(call.FieldAudioType, field.TypeString)
	}
	if value, ok := _u.mutation.DateTime(); ok {
		_spec.SetField(call.FieldDateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Frequencies(); ok {
		_spec.SetField(call.FieldFrequencies, field.TypeString, value)
	}
	if value, ok := _u.mutation.Frequency(); ok {
		_spec.SetField(call.FieldFrequency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFrequency(); ok {
		_spec.AddField(call.FieldFrequency, field.TypeInt, value)
	}
	if _u.mutation.FrequencyCleared() {
		_spec.ClearField(call.FieldFrequency, field.TypeInt)
	}
	if value, ok := _u.mutation.Patches(); ok {
		_spec.SetField(call.FieldPatches, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(call.FieldSource, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSource(); ok {
		_spec.AddField(call.FieldSource, field.TypeInt, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(call.FieldSource, field.TypeInt)
	}
	if value, ok := _u.mutation.Sources(); ok {
		_spec.SetField(call.FieldSources, field.TypeString, value)
	}
	if value, ok := _u.mutation.System(); ok {
		_spec.SetField(call.FieldSystem, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSystem(); ok {
		_spec.AddField(call.FieldSystem, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Talkgroup(); ok {
		_spec.SetField(call.FieldTalkgroup, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTalkgroup(); ok {
		_spec.AddField(call.FieldTalkgroup, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{call.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CallUpdateOne is the builder for updating a single Call entity.
type CallUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CallMutation
}

// SetAudio sets the "audio" field.
func (_u *CallUpdateOne) SetAudio(v []byte) *CallUpdateOne {
	_u.mutation.SetAudio(v)
	return _u
}

// SetAudioName sets the "audio_name" field.
func (_u *CallUpdateOne) SetAudioName(v string) *CallUpdateOne {
	_u.mutation.SetAudioName(v)
	return _u
}

// SetNillableAudioName sets the "audio_name" field if the given value is not nil.
func (_u *CallUpdateOne) SetNillableAudioName(v *string) *CallUpdateOne {
	if v != nil {
		_u.SetAudioName(*v)
	}
	return _u
}

// ClearAudioName clears the value of the "audio_name" field.
func (_u *CallUpdateOne) ClearAudioName() *CallUpdateOne {
	_u.mutation.ClearAudioName()
	return _u
}

// SetAudioType sets the "audio_type" field.
func (_u *CallUpdateOne) SetAudioType(v string) *CallUpdateOne {
	_u.mutation.SetAudioType(v)
	return _u
}

// SetNillableAudioType sets the "audio_type" field if the given value is not nil.
func (_u *CallUpdateOne) SetNillableAudioType(v *string) *CallUpdateOne {
	if v != nil {
		_u.SetAudioType(*v)
	}
	return _u
}

// ClearAudioType clears the value of the "audio_type" field.
func (_u *CallUpdateOne) ClearAudioType() *CallUpdateOne {
	_u.mutation.ClearAudioType()
	return _u
}

// SetDateTime sets the "date_time" field.
func (_u *CallUpdateOne) SetDateTime(v time.Time) *CallUpdateOne {
	_u.mutation.SetDateTime(v)
	return _u
}

// SetNillableDateTime sets the "date_time" field if the given value is not nil.
func (_u *CallUpdateOne) SetNillableDateTime(v *time.Time) *CallUpdateOne {
	if v != nil {
		_u.SetDateTime(*v)
	}
	return _u
}

// SetFrequencies sets the "frequencies" field.
func (_u *CallUpdateOne) SetFrequencies(v string) *CallUpdateOne {
	_u.mutation.SetFrequencies(v)
	return _u
}

// SetNillableFrequencies sets the "frequencies" field if the given value is not nil.
func (_u *CallUpdateOne) SetNillableFrequencies(v *string) *CallUpdateOne {
	if v != nil {
		_u.SetFrequencies(*v)
	}
	return _u
}

// SetFrequency sets the "frequency" field.
func (_u *CallUpdateOne) SetFrequency(v int) *CallUpdateOne {
	_u.mutation.ResetFrequency()
	_u.mutation.SetFrequency(v)
	return _u
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_u *CallUpdateOne) SetNillableFrequency(v *int) *CallUpdateOne {
	if v != nil {
		_u.SetFrequency(*v)
	}
	return _u
}

// AddFrequency adds value to the "frequency" field.
func (_u *CallUpdateOne) AddFrequency(v int) *CallUpdateOne {
	_u.mutation.AddFrequency(v)
	return _u
}

// ClearFrequency clears the value of the "frequency" field.
func (_u *CallUpdateOne) ClearFrequency() *CallUpdateOne {
	_u.mutation.ClearFrequency()
	return _u
}

// SetPatches sets the "patches" field.
func (_u *CallUpdateOne) SetPatches(v string) *CallUpdateOne {
	_u.mutation.SetPatches(v)
	return _u
}

// SetNillablePatches sets the "patches" field if the given value is not nil.
func (_u *CallUpdateOne) SetNillablePatches(v *string) *CallUpdateOne {
	if v != nil {
		_u.SetPatches(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *CallUpdateOne) SetSource(v int) *CallUpdateOne {
	_u.mutation.ResetSource()
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *CallUpdateOne) SetNillableSource(v *int) *CallUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// AddSource adds value to the "source" field.
func (_u *CallUpdateOne) AddSource(v int) *CallUpdateOne {
	_u.mutation.AddSource(v)
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *CallUpdateOne) ClearSource() *CallUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// SetSources sets the "sources" field.
func (_u *CallUpdateOne) SetSources(v string) *CallUpdateOne {
	_u.mutation.SetSources(v)
	return _u
}

// SetNillableSources sets the "sources" field if the given value is not nil.
func (_u *CallUpdateOne) SetNillableSources(v *string) *CallUpdateOne {
	if v != nil {
		_u.SetSources(*v)
	}
	return _u
}

// SetSystem sets the "system" field.
func (_u *CallUpdateOne) SetSystem(v int) *CallUpdateOne {
	_u.mutation.ResetSystem()
	_u.mutation.SetSystem(v)
	return _u
}

// SetNillableSystem sets the "system" field if the given value is not nil.
func (_u *CallUpdateOne) SetNillableSystem(v *int) *CallUpdateOne {
	if v != nil {
		_u.SetSystem(*v)
	}
	return _u
}

// AddSystem adds value to the "system" field.
func (_u *CallUpdateOne) AddSystem(v int) *CallUpdateOne {
	_u.mutation.AddSystem(v)
	return _u
}

// SetTalkgroup sets the "talkgroup" field.
func (_u *CallUpdateOne) SetTalkgroup(v int) *CallUpdateOne {
	_u.mutation.ResetTalkgroup()
	_u.mutation.SetTalkgroup(v)
	return _u
}

// SetNillableTalkgroup sets the "talkgroup" field if the given value is not nil.
func (_u *CallUpdateOne) SetNillableTalkgroup(v *int) *CallUpdateOne {
	if v != nil {
		_u.SetTalkgroup(*v)
	}
	return _u
}

// AddTalkgroup adds value to the "talkgroup" field.
func (_u *CallUpdateOne) AddTalkgroup(v int) *CallUpdateOne {
	_u.mutation.AddTalkgroup(v)
	return _u
}

// Mutation returns the CallMutation object of the builder.
func (_u *CallUpdateOne) Mutation() *CallMutation {
	return _u.mutation
}

// Where appends a list predicates to the CallUpdate builder.
func (_u *CallUpdateOne) Where(ps ...predicate.Call) *CallUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CallUpdateOne) Select(field string, fields ...string) *CallUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Call entity.
func (_u *CallUpdateOne) Save(ctx context.Context) (*Call, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CallUpdateOne) SaveX(ctx context.Context) *Call {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CallUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CallUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CallUpdateOne) sqlSave(ctx context.Context) (_node *Call, err error) {
	_spec := sqlgraph.NewUpdateSpec(call.Table, call.Columns, sqlgraph.NewFieldSpec(call.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Call.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, call.FieldID)
		for _, f := range fields {
			if !call.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != call.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Audio(); ok {
		_spec.SetField(call.FieldAudio, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.AudioName(); ok {
		_spec.SetField(call.FieldAudioName, field.TypeString, value)
	}
	if _u.mutation.AudioNameCleared() {
		_spec.ClearField(call.FieldAudioName, field.TypeString)
	}
	if value, ok := _u.mutation.AudioType(); ok {
		_spec.SetField(call.FieldAudioType, field.TypeString, value)
	}
	if _u.mutation.AudioTypeCleared() {
		_spec.ClearField(call.FieldAudioType, field.TypeString)
	}
	if value, ok := _u.mutation.DateTime(); ok {
		_spec.SetField(call.FieldDateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Frequencies(); ok {
		_spec.SetField(call.FieldFrequencies, field.TypeString, value)
	}
	if value, ok := _u.mutation.Frequency(); ok {
		_spec.SetField(call.FieldFrequency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFrequency(); ok {
		_spec.AddField(call.FieldFrequency, field.TypeInt, value)
	}
	if _u.mutation.FrequencyCleared() {
		_spec.ClearField(call.FieldFrequency, field.TypeInt)
	}
	if value, ok := _u.mutation.Patches(); ok {
		_spec.SetField(call.FieldPatches, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(call.FieldSource, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSource(); ok {
		_spec.AddField(call.FieldSource, field.TypeInt, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(call.FieldSource, field.TypeInt)
	}
	if value, ok := _u.mutation.Sources(); ok {
		_spec.SetField(call.FieldSources, field.TypeString, value)
	}
	if value, ok := _u.mutation.System(); ok {
		_spec.SetField(call.FieldSystem, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSystem(); ok {
		_spec.AddField(call.FieldSystem, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Talkgroup(); ok {
		_spec.SetField(call.FieldTalkgroup, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTalkgroup(); ok {
		_spec.AddField(call.FieldTalkgroup, field.TypeInt, value)
	}
	_node = &Call{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{call.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
