// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/call"
)

// CallCreate is the builder for creating a Call entity.
type CallCreate struct {
	config
	mutation *CallMutation
	hooks    []Hook
}

// SetAudio sets the "audio" field.
func (_c *CallCreate) SetAudio(v []byte) *CallCreate {
	_c.mutation.SetAudio(v)
	return _c
}

// SetAudioName sets the "audio_name" field.
func (_c *CallCreate) SetAudioName(v string) *CallCreate {
	_c.mutation.SetAudioName(v)
	return _c
}

// SetNillableAudioName sets the "audio_name" field if the given value is not nil.
func (_c *CallCreate) SetNillableAudioName(v *string) *CallCreate {
	if v != nil {
		_c.SetAudioName(*v)
	}
	return _c
}

// SetAudioType sets the "audio_type" field.
func (_c *CallCreate) SetAudioType(v string) *CallCreate {
	_c.mutation.SetAudioType(v)
	return _c
}

// SetNillableAudioType sets the "audio_type" field if the given value is not nil.
func (_c *CallCreate) SetNillableAudioType(v *string) *CallCreate {
	if v != nil {
		_c.SetAudioType(*v)
	}
	return _c
}

// SetDateTime sets the "date_time" field.
func (_c *CallCreate) SetDateTime(v time.Time) *CallCreate {
	_c.mutation.SetDateTime(v)
	return _c
}

// SetFrequencies sets the "frequencies" field.
func (_c *CallCreate) SetFrequencies(v string) *CallCreate {
	_c.mutation.SetFrequencies(v)
	return _c
}

// SetFrequency sets the "frequency" field.
func (_c *CallCreate) SetFrequency(v int) *CallCreate {
	_c.mutation.SetFrequency(v)
	return _c
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_c *CallCreate) SetNillableFrequency(v *int) *CallCreate {
	if v != nil {
		_c.SetFrequency(*v)
	}
	return _c
}

// SetPatches sets the "patches" field.
func (_c *CallCreate) SetPatches(v string) *CallCreate {
	_c.mutation.SetPatches(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *CallCreate) SetSource(v int) *CallCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *CallCreate) SetNillableSource(v *int) *CallCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSources sets the "sources" field.
func (_c *CallCreate) SetSources(v string) *CallCreate {
	_c.mutation.SetSources(v)
	return _c
}

// SetSystem sets the "system" field.
func (_c *CallCreate) SetSystem(v int) *CallCreate {
	_c.mutation.SetSystem(v)
	return _c
}

// SetTalkgroup sets the "talkgroup" field.
func (_c *CallCreate) SetTalkgroup(v int) *CallCreate {
	_c.mutation.SetTalkgroup(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CallCreate) SetID(v int) *CallCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CallMutation object of the builder.
func (_c *CallCreate) Mutation() *CallMutation {
	return _c.mutation
}

// Save creates the Call in the database.
func (_c *CallCreate) Save(ctx context.Context) (*Call, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CallCreate) SaveX(ctx context.Context) *Call {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CallCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CallCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CallCreate) check() error {
	if _, ok := _c.mutation.Audio(); !ok {
		return &ValidationError{Name: "audio", err: errors.New(`ent: missing required field "Call.audio"`)}
	}
	if _, ok := _c.mutation.DateTime(); !ok {
		return &ValidationError{Name: "date_time", err: errors.New(`ent: missing required field "Call.date_time"`)}
	}
	if _, ok := _c.mutation.Frequencies(); !ok {
		return &ValidationError{Name: "frequencies", err: errors.New(`ent: missing required field "Call.frequencies"`)}
	}
	if _, ok := _c.mutation.Patches(); !ok {
		return &ValidationError{Name: "patches", err: errors.New(`ent: missing required field "Call.patches"`)}
	}
	if _, ok := _c.mutation.Sources(); !ok {
		return &ValidationError{Name: "sources", err: errors.New(`ent: missing required field "Call.sources"`)}
	}
	if _, ok := _c.mutation.System(); !ok {
		return &ValidationError{Name: "system", err: errors.New(`ent: missing required field "Call.system"`)}
	}
	if _, ok := _c.mutation.Talkgroup(); !ok {
		return &ValidationError{Name: "talkgroup", err: errors.New(`ent: missing required field "Call.talkgroup"`)}
	}
	return nil
}

func (_c *CallCreate) sqlSave(ctx context.Context) (*Call, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CallCreate) createSpec() (*Call, *sqlgraph.CreateSpec) {
	var (
		_node = &Call{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(call.Table, sqlgraph.NewFieldSpec(call.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Audio(); ok {
		_spec.SetField(call.FieldAudio, field.TypeBytes, value)
		_node.Audio = value
	}
	if value, ok := _c.mutation.AudioName(); ok {
		_spec.SetField(call.FieldAudioName, field.TypeString, value)
		_node.AudioName = &value
	}
	if value, ok := _c.mutation.AudioType(); ok {
		_spec.SetField(call.FieldAudioType, field.TypeString, value)
		_node.AudioType = &value
	}
	if value, ok := _c.mutation.DateTime(); ok {
		_spec.SetField(call.FieldDateTime, field.TypeTime, value)
		_node.DateTime = value
	}
	if value, ok := _c.mutation.Frequencies(); ok {
		_spec.SetField(call.FieldFrequencies, field.TypeString, value)
		_node.Frequencies = value
	}
	if value, ok := _c.mutation.Frequency(); ok {
		_spec.SetField(call.FieldFrequency, field.TypeInt, value)
		_node.Frequency = &value
	}
	if value, ok := _c.mutation.Patches(); ok {
		_spec.SetField(call.FieldPatches, field.TypeString, value)
		_node.Patches = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(call.FieldSource, field.TypeInt, value)
		_node.Source = &value
	}
	if value, ok := _c.mutation.Sources(); ok {
		_spec.SetField(call.FieldSources, field.TypeString, value)
		_node.Sources = value
	}
	if value, ok := _c.mutation.System(); ok {
		_spec.SetField(call.FieldSystem, field.TypeInt, value)
		_node.System = value
	}
	if value, ok := _c.mutation.Talkgroup(); ok {
		_spec.SetField(call.FieldTalkgroup, field.TypeInt, value)
		_node.Talkgroup = value
	}
	return _node, _spec
}

// CallCreateBulk is the builder for creating many Call entities in bulk.
type CallCreateBulk struct {
	config
	err      error
	builders []*CallCreate
}

// Save creates the Call entities in the database.
func (_c *CallCreateBulk) Save(ctx context.Context) ([]*Call, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Call, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CallMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CallCreateBulk) SaveX(ctx context.Context) []*Call {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CallCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CallCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
