// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/call"
)

// CallCreate is the builder for creating a Call entity.
type CallCreate struct {
	config
	mutation *CallMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAudio sets the "audio" field.
func (_c *CallCreate) SetAudio(v []byte) *CallCreate {
	_c.mutation.SetAudio(v)
	return _c
}

// SetAudioName sets the "audio_name" field.
func (_c *CallCreate) SetAudioName(v string) *CallCreate {
	_c.mutation.SetAudioName(v)
	return _c
}

// SetNillableAudioName sets the "audio_name" field if the given value is not nil.
func (_c *CallCreate) SetNillableAudioName(v *string) *CallCreate {
	if v != nil {
		_c.SetAudioName(*v)
	}
	return _c
}

// SetAudioType sets the "audio_type" field.
func (_c *CallCreate) SetAudioType(v string) *CallCreate {
	_c.mutation.SetAudioType(v)
	return _c
}

// SetNillableAudioType sets the "audio_type" field if the given value is not nil.
func (_c *CallCreate) SetNillableAudioType(v *string) *CallCreate {
	if v != nil {
		_c.SetAudioType(*v)
	}
	return _c
}

// SetDateTime sets the "date_time" field.
func (_c *CallCreate) SetDateTime(v time.Time) *CallCreate {
	_c.mutation.SetDateTime(v)
	return _c
}

// SetFrequencies sets the "frequencies" field.
func (_c *CallCreate) SetFrequencies(v string) *CallCreate {
	_c.mutation.SetFrequencies(v)
	return _c
}

// SetFrequency sets the "frequency" field.
func (_c *CallCreate) SetFrequency(v int) *CallCreate {
	_c.mutation.SetFrequency(v)
	return _c
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_c *CallCreate) SetNillableFrequency(v *int) *CallCreate {
	if v != nil {
		_c.SetFrequency(*v)
	}
	return _c
}

// SetPatches sets the "patches" field.
func (_c *CallCreate) SetPatches(v string) *CallCreate {
	_c.mutation.SetPatches(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *CallCreate) SetSource(v int) *CallCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *CallCreate) SetNillableSource(v *int) *CallCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSources sets the "sources" field.
func (_c *CallCreate) SetSources(v string) *CallCreate {
	_c.mutation.SetSources(v)
	return _c
}

// SetSystem sets the "system" field.
func (_c *CallCreate) SetSystem(v int) *CallCreate {
	_c.mutation.SetSystem(v)
	return _c
}

// SetTalkgroup sets the "talkgroup" field.
func (_c *CallCreate) SetTalkgroup(v int) *CallCreate {
	_c.mutation.SetTalkgroup(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CallCreate) SetID(v int) *CallCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CallMutation object of the builder.
func (_c *CallCreate) Mutation() *CallMutation {
	return _c.mutation
}

// Save creates the Call in the database.
func (_c *CallCreate) Save(ctx context.Context) (*Call, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CallCreate) SaveX(ctx context.Context) *Call {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CallCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CallCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CallCreate) check() error {
	if _, ok := _c.mutation.Audio(); !ok {
		return &ValidationError{Name: "audio", err: errors.New(`ent: missing required field "Call.audio"`)}
	}
	if _, ok := _c.mutation.DateTime(); !ok {
		return &ValidationError{Name: "date_time", err: errors.New(`ent: missing required field "Call.date_time"`)}
	}
	if _, ok := _c.mutation.Frequencies(); !ok {
		return &ValidationError{Name: "frequencies", err: errors.New(`ent: missing required field "Call.frequencies"`)}
	}
	if _, ok := _c.mutation.Patches(); !ok {
		return &ValidationError{Name: "patches", err: errors.New(`ent: missing required field "Call.patches"`)}
	}
	if _, ok := _c.mutation.Sources(); !ok {
		return &ValidationError{Name: "sources", err: errors.New(`ent: missing required field "Call.sources"`)}
	}
	if _, ok := _c.mutation.System(); !ok {
		return &ValidationError{Name: "system", err: errors.New(`ent: missing required field "Call.system"`)}
	}
	if _, ok := _c.mutation.Talkgroup(); !ok {
		return &ValidationError{Name: "talkgroup", err: errors.New(`ent: missing required field "Call.talkgroup"`)}
	}
	return nil
}

func (_c *CallCreate) sqlSave(ctx context.Context) (*Call, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CallCreate) createSpec() (*Call, *sqlgraph.CreateSpec) {
	var (
		_node = &Call{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(call.Table, sqlgraph.NewFieldSpec(call.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Audio(); ok {
		_spec.SetField(call.FieldAudio, field.TypeBytes, value)
		_node.Audio = value
	}
	if value, ok := _c.mutation.AudioName(); ok {
		_spec.SetField(call.FieldAudioName, field.TypeString, value)
		_node.AudioName = &value
	}
	if value, ok := _c.mutation.AudioType(); ok {
		_spec.SetField(call.FieldAudioType, field.TypeString, value)
		_node.AudioType = &value
	}
	if value, ok := _c.mutation.DateTime(); ok {
		_spec.SetField(call.FieldDateTime, field.TypeTime, value)
		_node.DateTime = value
	}
	if value, ok := _c.mutation.Frequencies(); ok {
		_spec.SetField(call.FieldFrequencies, field.TypeString, value)
		_node.Frequencies = value
	}
	if value, ok := _c.mutation.Frequency(); ok {
		_spec.SetField(call.FieldFrequency, field.TypeInt, value)
		_node.Frequency = &value
	}
	if value, ok := _c.mutation.Patches(); ok {
		_spec.SetField(call.FieldPatches, field.TypeString, value)
		_node.Patches = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(call.FieldSource, field.TypeInt, value)
		_node.Source = &value
	}
	if value, ok := _c.mutation.Sources(); ok {
		_spec.SetField(call.FieldSources, field.TypeString, value)
		_node.Sources = value
	}
	if value, ok := _c.mutation.System(); ok {
		_spec.SetField(call.FieldSystem, field.TypeInt, value)
		_node.System = value
	}
	if value, ok := _c.mutation.Talkgroup(); ok {
		_spec.SetField(call.FieldTalkgroup, field.TypeInt, value)
		_node.Talkgroup = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Call.Create().
//		SetAudio(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CallUpsert) {
//			SetAudio(v+v).
//		}).
//		Exec(ctx)
func (_c *CallCreate) OnConflict(opts ...sql.ConflictOption) *CallUpsertOne {
	_c.conflict = opts
	return &CallUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Call.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CallCreate) OnConflictColumns(columns ...string) *CallUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CallUpsertOne{
		create: _c,
	}
}

type (
	// CallUpsertOne is the builder for "upsert"-ing
	//  one Call node.
	CallUpsertOne struct {
		create *CallCreate
	}

	// CallUpsert is the "OnConflict" setter.
	CallUpsert struct {
		*sql.UpdateSet
	}
)

// SetAudio sets the "audio" field.
func (u *CallUpsert) SetAudio(v []byte) *CallUpsert {
	u.Set(call.FieldAudio, v)
	return u
}

// UpdateAudio sets the "audio" field to the value that was provided on create.
func (u *CallUpsert) UpdateAudio() *CallUpsert {
	u.SetExcluded(call.FieldAudio)
	return u
}

// SetAudioName sets the "audio_name" field.
func (u *CallUpsert) SetAudioName(v string) *CallUpsert {
	u.Set(call.FieldAudioName, v)
	return u
}

// UpdateAudioName sets the "audio_name" field to the value that was provided on create.
func (u *CallUpsert) UpdateAudioName() *CallUpsert {
	u.SetExcluded(call.FieldAudioName)
	return u
}

// ClearAudioName clears the value of the "audio_name" field.
func (u *CallUpsert) ClearAudioName() *CallUpsert {
	u.SetNull(call.FieldAudioName)
	return u
}

// SetAudioType sets the "audio_type" field.
func (u *CallUpsert) SetAudioType(v string) *CallUpsert {
	u.Set(call.FieldAudioType, v)
	return u
}

// UpdateAudioType sets the "audio_type" field to the value that was provided on create.
func (u *CallUpsert) UpdateAudioType() *CallUpsert {
	u.SetExcluded(call.FieldAudioType)
	return u
}

// ClearAudioType clears the value of the "audio_type" field.
func (u *CallUpsert) ClearAudioType() *CallUpsert {
	u.SetNull(call.FieldAudioType)
	return u
}

// SetDateTime sets the "date_time" field.
func (u *CallUpsert) SetDateTime(v time.Time) *CallUpsert {
	u.Set(call.FieldDateTime, v)
	return u
}

// UpdateDateTime sets the "date_time" field to the value that was provided on create.
func (u *CallUpsert) UpdateDateTime() *CallUpsert {
	u.SetExcluded(call.FieldDateTime)
	return u
}

// SetFrequencies sets the "frequencies" field.
func (u *CallUpsert) SetFrequencies(v string) *CallUpsert {
	u.Set(call.FieldFrequencies, v)
	return u
}

// UpdateFrequencies sets the "frequencies" field to the value that was provided on create.
func (u *CallUpsert) UpdateFrequencies() *CallUpsert {
	u.SetExcluded(call.FieldFrequencies)
	return u
}

// SetFrequency sets the "frequency" field.
func (u *CallUpsert) SetFrequency(v int) *CallUpsert {
	u.Set(call.FieldFrequency, v)
	return u
}

// UpdateFrequency sets the "frequency" field to the value that was provided on create.
func (u *CallUpsert) UpdateFrequency() *CallUpsert {
	u.SetExcluded(call.FieldFrequency)
	return u
}

// AddFrequency adds v to the "frequency" field.
func (u *CallUpsert) AddFrequency(v int) *CallUpsert {
	u.Add(call.FieldFrequency, v)
	return u
}

// ClearFrequency clears the value of the "frequency" field.
func (u *CallUpsert) ClearFrequency() *CallUpsert {
	u.SetNull(call.FieldFrequency)
	return u
}

// SetPatches sets the "patches" field.
func (u *CallUpsert) SetPatches(v string) *CallUpsert {
	u.Set(call.FieldPatches, v)
	return u
}

// UpdatePatches sets the "patches" field to the value that was provided on create.
func (u *CallUpsert) UpdatePatches() *CallUpsert {
	u.SetExcluded(call.FieldPatches)
	return u
}

// SetSource sets the "source" field.
func (u *CallUpsert) SetSource(v int) *CallUpsert {
	u.Set(call.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CallUpsert) UpdateSource() *CallUpsert {
	u.SetExcluded(call.FieldSource)
	return u
}

// AddSource adds v to the "source" field.
func (u *CallUpsert) AddSource(v int) *CallUpsert {
	u.Add(call.FieldSource, v)
	return u
}

// ClearSource clears the value of the "source" field.
func (u *CallUpsert) ClearSource() *CallUpsert {
	u.SetNull(call.FieldSource)
	return u
}

// SetSources sets the "sources" field.
func (u *CallUpsert) SetSources(v string) *CallUpsert {
	u.Set(call.FieldSources, v)
	return u
}

// UpdateSources sets the "sources" field to the value that was provided on create.
func (u *CallUpsert) UpdateSources() *CallUpsert {
	u.SetExcluded(call.FieldSources)
	return u
}

// SetSystem sets the "system" field.
func (u *CallUpsert) SetSystem(v int) *CallUpsert {
	u.Set(call.FieldSystem, v)
	return u
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *CallUpsert) UpdateSystem() *CallUpsert {
	u.SetExcluded(call.FieldSystem)
	return u
}

// AddSystem adds v to the "system" field.
func (u *CallUpsert) AddSystem(v int) *CallUpsert {
	u.Add(call.FieldSystem, v)
	return u
}

// SetTalkgroup sets the "talkgroup" field.
func (u *CallUpsert) SetTalkgroup(v int) *CallUpsert {
	u.Set(call.FieldTalkgroup, v)
	return u
}

// UpdateTalkgroup sets the "talkgroup" field to the value that was provided on create.
func (u *CallUpsert) UpdateTalkgroup() *CallUpsert {
	u.SetExcluded(call.FieldTalkgroup)
	return u
}

// AddTalkgroup adds v to the "talkgroup" field.
func (u *CallUpsert) AddTalkgroup(v int) *CallUpsert {
	u.Add(call.FieldTalkgroup, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Call.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(call.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CallUpsertOne) UpdateNewValues() *CallUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(call.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Call.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CallUpsertOne) Ignore() *CallUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CallUpsertOne) DoNothing() *CallUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CallCreate.OnConflict
// documentation for more info.
func (u *CallUpsertOne) Update(set func(*CallUpsert)) *CallUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CallUpsert{UpdateSet: update})
	}))
	return u
}

// SetAudio sets the "audio" field.
func (u *CallUpsertOne) SetAudio(v []byte) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.SetAudio(v)
	})
}

// UpdateAudio sets the "audio" field to the value that was provided on create.
func (u *CallUpsertOne) UpdateAudio() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.UpdateAudio()
	})
}

// SetAudioName sets the "audio_name" field.
func (u *CallUpsertOne) SetAudioName(v string) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.SetAudioName(v)
	})
}

// UpdateAudioName sets the "audio_name" field to the value that was provided on create.
func (u *CallUpsertOne) UpdateAudioName() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.UpdateAudioName()
	})
}

// ClearAudioName clears the value of the "audio_name" field.
func (u *CallUpsertOne) ClearAudioName() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.ClearAudioName()
	})
}

// SetAudioType sets the "audio_type" field.
func (u *CallUpsertOne) SetAudioType(v string) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.SetAudioType(v)
	})
}

// UpdateAudioType sets the "audio_type" field to the value that was provided on create.
func (u *CallUpsertOne) UpdateAudioType() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.UpdateAudioType()
	})
}

// ClearAudioType clears the value of the "audio_type" field.
func (u *CallUpsertOne) ClearAudioType() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.ClearAudioType()
	})
}

// SetDateTime sets the "date_time" field.
func (u *CallUpsertOne) SetDateTime(v time.Time) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.SetDateTime(v)
	})
}

// UpdateDateTime sets the "date_time" field to the value that was provided on create.
func (u *CallUpsertOne) UpdateDateTime() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.UpdateDateTime()
	})
}

// SetFrequencies sets the "frequencies" field.
func (u *CallUpsertOne) SetFrequencies(v string) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.SetFrequencies(v)
	})
}

// UpdateFrequencies sets the "frequencies" field to the value that was provided on create.
func (u *CallUpsertOne) UpdateFrequencies() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.UpdateFrequencies()
	})
}

// SetFrequency sets the "frequency" field.
func (u *CallUpsertOne) SetFrequency(v int) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.SetFrequency(v)
	})
}

// AddFrequency adds v to the "frequency" field.
func (u *CallUpsertOne) AddFrequency(v int) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.AddFrequency(v)
	})
}

// UpdateFrequency sets the "frequency" field to the value that was provided on create.
func (u *CallUpsertOne) UpdateFrequency() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.UpdateFrequency()
	})
}

// ClearFrequency clears the value of the "frequency" field.
func (u *CallUpsertOne) ClearFrequency() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.ClearFrequency()
	})
}

// SetPatches sets the "patches" field.
func (u *CallUpsertOne) SetPatches(v string) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.SetPatches(v)
	})
}

// UpdatePatches sets the "patches" field to the value that was provided on create.
func (u *CallUpsertOne) UpdatePatches() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.UpdatePatches()
	})
}

// SetSource sets the "source" field.
func (u *CallUpsertOne) SetSource(v int) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.SetSource(v)
	})
}

// AddSource adds v to the "source" field.
func (u *CallUpsertOne) AddSource(v int) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.AddSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CallUpsertOne) UpdateSource() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.UpdateSource()
	})
}

// ClearSource clears the value of the "source" field.
func (u *CallUpsertOne) ClearSource() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.ClearSource()
	})
}

// SetSources sets the "sources" field.
func (u *CallUpsertOne) SetSources(v string) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.SetSources(v)
	})
}

// UpdateSources sets the "sources" field to the value that was provided on create.
func (u *CallUpsertOne) UpdateSources() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.UpdateSources()
	})
}

// SetSystem sets the "system" field.
func (u *CallUpsertOne) SetSystem(v int) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.SetSystem(v)
	})
}

// AddSystem adds v to the "system" field.
func (u *CallUpsertOne) AddSystem(v int) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.AddSystem(v)
	})
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *CallUpsertOne) UpdateSystem() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.UpdateSystem()
	})
}

// SetTalkgroup sets the "talkgroup" field.
func (u *CallUpsertOne) SetTalkgroup(v int) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.SetTalkgroup(v)
	})
}

// AddTalkgroup adds v to the "talkgroup" field.
func (u *CallUpsertOne) AddTalkgroup(v int) *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.AddTalkgroup(v)
	})
}

// UpdateTalkgroup sets the "talkgroup" field to the value that was provided on create.
func (u *CallUpsertOne) UpdateTalkgroup() *CallUpsertOne {
	return u.Update(func(s *CallUpsert) {
		s.UpdateTalkgroup()
	})
}

// Exec executes the query.
func (u *CallUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CallCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CallUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CallUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CallUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CallCreateBulk is the builder for creating many Call entities in bulk.
type CallCreateBulk struct {
	config
	err      error
	builders []*CallCreate
	conflict []sql.ConflictOption
}

// Save creates the Call entities in the database.
func (_c *CallCreateBulk) Save(ctx context.Context) ([]*Call, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Call, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CallMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CallCreateBulk) SaveX(ctx context.Context) []*Call {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CallCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CallCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Call.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CallUpsert) {
//			SetAudio(v+v).
//		}).
//		Exec(ctx)
func (_c *CallCreateBulk) OnConflict(opts ...sql.ConflictOption) *CallUpsertBulk {
	_c.conflict = opts
	return &CallUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Call.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CallCreateBulk) OnConflictColumns(columns ...string) *CallUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CallUpsertBulk{
		create: _c,
	}
}

// CallUpsertBulk is the builder for "upsert"-ing
// a bulk of Call nodes.
type CallUpsertBulk struct {
	create *CallCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Call.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(call.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CallUpsertBulk) UpdateNewValues() *CallUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(call.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Call.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CallUpsertBulk) Ignore() *CallUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CallUpsertBulk) DoNothing() *CallUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CallCreateBulk.OnConflict
// documentation for more info.
func (u *CallUpsertBulk) Update(set func(*CallUpsert)) *CallUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CallUpsert{UpdateSet: update})
	}))
	return u
}

// SetAudio sets the "audio" field.
func (u *CallUpsertBulk) SetAudio(v []byte) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.SetAudio(v)
	})
}

// UpdateAudio sets the "audio" field to the value that was provided on create.
func (u *CallUpsertBulk) UpdateAudio() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.UpdateAudio()
	})
}

// SetAudioName sets the "audio_name" field.
func (u *CallUpsertBulk) SetAudioName(v string) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.SetAudioName(v)
	})
}

// UpdateAudioName sets the "audio_name" field to the value that was provided on create.
func (u *CallUpsertBulk) UpdateAudioName() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.UpdateAudioName()
	})
}

// ClearAudioName clears the value of the "audio_name" field.
func (u *CallUpsertBulk) ClearAudioName() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.ClearAudioName()
	})
}

// SetAudioType sets the "audio_type" field.
func (u *CallUpsertBulk) SetAudioType(v string) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.SetAudioType(v)
	})
}

// UpdateAudioType sets the "audio_type" field to the value that was provided on create.
func (u *CallUpsertBulk) UpdateAudioType() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.UpdateAudioType()
	})
}

// ClearAudioType clears the value of the "audio_type" field.
func (u *CallUpsertBulk) ClearAudioType() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.ClearAudioType()
	})
}

// SetDateTime sets the "date_time" field.
func (u *CallUpsertBulk) SetDateTime(v time.Time) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.SetDateTime(v)
	})
}

// UpdateDateTime sets the "date_time" field to the value that was provided on create.
func (u *CallUpsertBulk) UpdateDateTime() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.UpdateDateTime()
	})
}

// SetFrequencies sets the "frequencies" field.
func (u *CallUpsertBulk) SetFrequencies(v string) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.SetFrequencies(v)
	})
}

// UpdateFrequencies sets the "frequencies" field to the value that was provided on create.
func (u *CallUpsertBulk) UpdateFrequencies() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.UpdateFrequencies()
	})
}

// SetFrequency sets the "frequency" field.
func (u *CallUpsertBulk) SetFrequency(v int) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.SetFrequency(v)
	})
}

// AddFrequency adds v to the "frequency" field.
func (u *CallUpsertBulk) AddFrequency(v int) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.AddFrequency(v)
	})
}

// UpdateFrequency sets the "frequency" field to the value that was provided on create.
func (u *CallUpsertBulk) UpdateFrequency() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.UpdateFrequency()
	})
}

// ClearFrequency clears the value of the "frequency" field.
func (u *CallUpsertBulk) ClearFrequency() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.ClearFrequency()
	})
}

// SetPatches sets the "patches" field.
func (u *CallUpsertBulk) SetPatches(v string) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.SetPatches(v)
	})
}

// UpdatePatches sets the "patches" field to the value that was provided on create.
func (u *CallUpsertBulk) UpdatePatches() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.UpdatePatches()
	})
}

// SetSource sets the "source" field.
func (u *CallUpsertBulk) SetSource(v int) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.SetSource(v)
	})
}

// AddSource adds v to the "source" field.
func (u *CallUpsertBulk) AddSource(v int) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.AddSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CallUpsertBulk) UpdateSource() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.UpdateSource()
	})
}

// ClearSource clears the value of the "source" field.
func (u *CallUpsertBulk) ClearSource() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.ClearSource()
	})
}

// SetSources sets the "sources" field.
func (u *CallUpsertBulk) SetSources(v string) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.SetSources(v)
	})
}

// UpdateSources sets the "sources" field to the value that was provided on create.
func (u *CallUpsertBulk) UpdateSources() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.UpdateSources()
	})
}

// SetSystem sets the "system" field.
func (u *CallUpsertBulk) SetSystem(v int) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.SetSystem(v)
	})
}

// AddSystem adds v to the "system" field.
func (u *CallUpsertBulk) AddSystem(v int) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.AddSystem(v)
	})
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *CallUpsertBulk) UpdateSystem() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.UpdateSystem()
	})
}

// SetTalkgroup sets the "talkgroup" field.
func (u *CallUpsertBulk) SetTalkgroup(v int) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.SetTalkgroup(v)
	})
}

// AddTalkgroup adds v to the "talkgroup" field.
func (u *CallUpsertBulk) AddTalkgroup(v int) *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.AddTalkgroup(v)
	})
}

// UpdateTalkgroup sets the "talkgroup" field to the value that was provided on create.
func (u *CallUpsertBulk) UpdateTalkgroup() *CallUpsertBulk {
	return u.Update(func(s *CallUpsert) {
		s.UpdateTalkgroup()
	})
}

// Exec executes the query.
func (u *CallUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CallCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CallCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CallUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
