// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/dirwatch"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/predicate"
)

// DirwatchDelete is the builder for deleting a Dirwatch entity.
type DirwatchDelete struct {
	config
	hooks    []Hook
	mutation *DirwatchMutation
}

// Where appends a list predicates to the DirwatchDelete builder.
func (_d *DirwatchDelete) Where(ps ...predicate.Dirwatch) *DirwatchDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DirwatchDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DirwatchDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DirwatchDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dirwatch.Table, sqlgraph.NewFieldSpec(dirwatch.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DirwatchDeleteOne is the builder for deleting a single Dirwatch entity.
type DirwatchDeleteOne struct {
	_d *DirwatchDelete
}

// Where appends a list predicates to the DirwatchDelete builder.
func (_d *DirwatchDeleteOne) Where(ps ...predicate.Dirwatch) *DirwatchDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DirwatchDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dirwatch.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DirwatchDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
