// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/dirwatch"
)

// DirwatchCreate is the builder for creating a Dirwatch entity.
type DirwatchCreate struct {
	config
	mutation *DirwatchMutation
	hooks    []Hook
}

// SetDelay sets the "delay" field.
func (_c *DirwatchCreate) SetDelay(v int) *DirwatchCreate {
	_c.mutation.SetDelay(v)
	return _c
}

// SetNillableDelay sets the "delay" field if the given value is not nil.
func (_c *DirwatchCreate) SetNillableDelay(v *int) *DirwatchCreate {
	if v != nil {
		_c.SetDelay(*v)
	}
	return _c
}

// SetDeleteAfter sets the "delete_after" field.
func (_c *DirwatchCreate) SetDeleteAfter(v bool) *DirwatchCreate {
	_c.mutation.SetDeleteAfter(v)
	return _c
}

// SetNillableDeleteAfter sets the "delete_after" field if the given value is not nil.
func (_c *DirwatchCreate) SetNillableDeleteAfter(v *bool) *DirwatchCreate {
	if v != nil {
		_c.SetDeleteAfter(*v)
	}
	return _c
}

// SetDirectory sets the "directory" field.
func (_c *DirwatchCreate) SetDirectory(v string) *DirwatchCreate {
	_c.mutation.SetDirectory(v)
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *DirwatchCreate) SetDisabled(v bool) *DirwatchCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *DirwatchCreate) SetNillableDisabled(v *bool) *DirwatchCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetExtension sets the "extension" field.
func (_c *DirwatchCreate) SetExtension(v string) *DirwatchCreate {
	_c.mutation.SetExtension(v)
	return _c
}

// SetNillableExtension sets the "extension" field if the given value is not nil.
func (_c *DirwatchCreate) SetNillableExtension(v *string) *DirwatchCreate {
	if v != nil {
		_c.SetExtension(*v)
	}
	return _c
}

// SetFrequency sets the "frequency" field.
func (_c *DirwatchCreate) SetFrequency(v int) *DirwatchCreate {
	_c.mutation.SetFrequency(v)
	return _c
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_c *DirwatchCreate) SetNillableFrequency(v *int) *DirwatchCreate {
	if v != nil {
		_c.SetFrequency(*v)
	}
	return _c
}

// SetMask sets the "mask" field.
func (_c *DirwatchCreate) SetMask(v string) *DirwatchCreate {
	_c.mutation.SetMask(v)
	return _c
}

// SetNillableMask sets the "mask" field if the given value is not nil.
func (_c *DirwatchCreate) SetNillableMask(v *string) *DirwatchCreate {
	if v != nil {
		_c.SetMask(*v)
	}
	return _c
}

// SetOrder sets the "order" field.
func (_c *DirwatchCreate) SetOrder(v int) *DirwatchCreate {
	_c.mutation.SetOrder(v)
	return _c
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_c *DirwatchCreate) SetNillableOrder(v *int) *DirwatchCreate {
	if v != nil {
		_c.SetOrder(*v)
	}
	return _c
}

// SetSystemID sets the "system_id" field.
func (_c *DirwatchCreate) SetSystemID(v int) *DirwatchCreate {
	_c.mutation.SetSystemID(v)
	return _c
}

// SetNillableSystemID sets the "system_id" field if the given value is not nil.
func (_c *DirwatchCreate) SetNillableSystemID(v *int) *DirwatchCreate {
	if v != nil {
		_c.SetSystemID(*v)
	}
	return _c
}

// SetTalkgroupID sets the "talkgroup_id" field.
func (_c *DirwatchCreate) SetTalkgroupID(v int) *DirwatchCreate {
	_c.mutation.SetTalkgroupID(v)
	return _c
}

// SetNillableTalkgroupID sets the "talkgroup_id" field if the given value is not nil.
func (_c *DirwatchCreate) SetNillableTalkgroupID(v *int) *DirwatchCreate {
	if v != nil {
		_c.SetTalkgroupID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *DirwatchCreate) SetType(v string) *DirwatchCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *DirwatchCreate) SetNillableType(v *string) *DirwatchCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetUsePolling sets the "use_polling" field.
func (_c *DirwatchCreate) SetUsePolling(v bool) *DirwatchCreate {
	_c.mutation.SetUsePolling(v)
	return _c
}

// SetNillableUsePolling sets the "use_polling" field if the given value is not nil.
func (_c *DirwatchCreate) SetNillableUsePolling(v *bool) *DirwatchCreate {
	if v != nil {
		_c.SetUsePolling(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DirwatchCreate) SetID(v int) *DirwatchCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the DirwatchMutation object of the builder.
func (_c *DirwatchCreate) Mutation() *DirwatchMutation {
	return _c.mutation
}

// Save creates the Dirwatch in the database.
func (_c *DirwatchCreate) Save(ctx context.Context) (*Dirwatch, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DirwatchCreate) SaveX(ctx context.Context) *Dirwatch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DirwatchCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DirwatchCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DirwatchCreate) defaults() {
	if _, ok := _c.mutation.Delay(); !ok {
		v := dirwatch.DefaultDelay
		_c.mutation.SetDelay(v)
	}
	if _, ok := _c.mutation.DeleteAfter(); !ok {
		v := dirwatch.DefaultDeleteAfter
		_c.mutation.SetDeleteAfter(v)
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		v := dirwatch.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
	if _, ok := _c.mutation.UsePolling(); !ok {
		v := dirwatch.DefaultUsePolling
		_c.mutation.SetUsePolling(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DirwatchCreate) check() error {
	if _, ok := _c.mutation.Directory(); !ok {
		return &ValidationError{Name: "directory", err: errors.New(`ent: missing required field "Dirwatch.directory"`)}
	}
	return nil
}

func (_c *DirwatchCreate) sqlSave(ctx context.Context) (*Dirwatch, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DirwatchCreate) createSpec() (*Dirwatch, *sqlgraph.CreateSpec) {
	var (
		_node = &Dirwatch{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dirwatch.Table, sqlgraph.NewFieldSpec(dirwatch.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Delay(); ok {
		_spec.SetField(dirwatch.FieldDelay, field.TypeInt, value)
		_node.Delay = &value
	}
	if value, ok := _c.mutation.DeleteAfter(); ok {
		_spec.SetField(dirwatch.FieldDeleteAfter, field.TypeBool, value)
		_node.DeleteAfter = &value
	}
	if value, ok := _c.mutation.Directory(); ok {
		_spec.SetField(dirwatch.FieldDirectory, field.TypeString, value)
		_node.Directory = value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(dirwatch.FieldDisabled, field.TypeBool, value)
		_node.Disabled = &value
	}
	if value, ok := _c.mutation.Extension(); ok {
		_spec.SetField(dirwatch.FieldExtension, field.TypeString, value)
		_node.Extension = &value
	}
	if value, ok := _c.mutation.Frequency(); ok {
		_spec.SetField(dirwatch.FieldFrequency, field.TypeInt, value)
		_node.Frequency = &value
	}
	if value, ok := _c.mutation.Mask(); ok {
		_spec.SetField(dirwatch.FieldMask, field.TypeString, value)
		_node.Mask = &value
	}
	if value, ok := _c.mutation.Order(); ok {
		_spec.SetField(dirwatch.FieldOrder, field.TypeInt, value)
		_node.Order = &value
	}
	if value, ok := _c.mutation.SystemID(); ok {
		_spec.SetField(dirwatch.FieldSystemID, field.TypeInt, value)
		_node.SystemID = &value
	}
	if value, ok := _c.mutation.TalkgroupID(); ok {
		_spec.SetField(dirwatch.FieldTalkgroupID, field.TypeInt, value)
		_node.TalkgroupID = &value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(dirwatch.FieldType, field.TypeString, value)
		_node.Type = &value
	}
	if value, ok := _c.mutation.UsePolling(); ok {
		_spec.SetField(dirwatch.FieldUsePolling, field.TypeBool, value)
		_node.UsePolling = &value
	}
	return _node, _spec
}

// DirwatchCreateBulk is the builder for creating many Dirwatch entities in bulk.
type DirwatchCreateBulk struct {
	config
	err      error
	builders []*DirwatchCreate
}

// Save creates the Dirwatch entities in the database.
func (_c *DirwatchCreateBulk) Save(ctx context.Context) ([]*Dirwatch, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Dirwatch, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DirwatchMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DirwatchCreateBulk) SaveX(ctx context.Context) []*Dirwatch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DirwatchCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DirwatchCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
