// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/logentry"
)

// LogEntryCreate is the builder for creating a LogEntry entity.
type LogEntryCreate struct {
	config
	mutation *LogEntryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDateTime sets the "date_time" field.
func (_c *LogEntryCreate) SetDateTime(v time.Time) *LogEntryCreate {
	_c.mutation.SetDateTime(v)
	return _c
}

// SetLevel sets the "level" field.
func (_c *LogEntryCreate) SetLevel(v string) *LogEntryCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *LogEntryCreate) SetMessage(v string) *LogEntryCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetID sets the "id" field.
func (_c *LogEntryCreate) SetID(v int) *LogEntryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the LogEntryMutation object of the builder.
func (_c *LogEntryCreate) Mutation() *LogEntryMutation {
	return _c.mutation
}

// Save creates the LogEntry in the database.
func (_c *LogEntryCreate) Save(ctx context.Context) (*LogEntry, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LogEntryCreate) SaveX(ctx context.Context) *LogEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LogEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LogEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LogEntryCreate) check() error {
	if _, ok := _c.mutation.DateTime(); !ok {
		return &ValidationError{Name: "date_time", err: errors.New(`ent: missing required field "LogEntry.date_time"`)}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "LogEntry.level"`)}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "LogEntry.message"`)}
	}
	return nil
}

func (_c *LogEntryCreate) sqlSave(ctx context.Context) (*LogEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LogEntryCreate) createSpec() (*LogEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &LogEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(logentry.Table, sqlgraph.NewFieldSpec(logentry.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DateTime(); ok {
		_spec.SetField(logentry.FieldDateTime, field.TypeTime, value)
		_node.DateTime = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(logentry.FieldLevel, field.TypeString, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(logentry.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LogEntry.Create().
//		SetDateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LogEntryUpsert) {
//			SetDateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *LogEntryCreate) OnConflict(opts ...sql.ConflictOption) *LogEntryUpsertOne {
	_c.conflict = opts
	return &LogEntryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LogEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LogEntryCreate) OnConflictColumns(columns ...string) *LogEntryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LogEntryUpsertOne{
		create: _c,
	}
}

type (
	// LogEntryUpsertOne is the builder for "upsert"-ing
	//  one LogEntry node.
	LogEntryUpsertOne struct {
		create *LogEntryCreate
	}

	// LogEntryUpsert is the "OnConflict" setter.
	LogEntryUpsert struct {
		*sql.UpdateSet
	}
)

// SetDateTime sets the "date_time" field.
func (u *LogEntryUpsert) SetDateTime(v time.Time) *LogEntryUpsert {
	u.Set(logentry.FieldDateTime, v)
	return u
}

// UpdateDateTime sets the "date_time" field to the value that was provided on create.
func (u *LogEntryUpsert) UpdateDateTime() *LogEntryUpsert {
	u.SetExcluded(logentry.FieldDateTime)
	return u
}

// SetLevel sets the "level" field.
func (u *LogEntryUpsert) SetLevel(v string) *LogEntryUpsert {
	u.Set(logentry.FieldLevel, v)
	return u
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *LogEntryUpsert) UpdateLevel() *LogEntryUpsert {
	u.SetExcluded(logentry.FieldLevel)
	return u
}

// SetMessage sets the "message" field.
func (u *LogEntryUpsert) SetMessage(v string) *LogEntryUpsert {
	u.Set(logentry.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *LogEntryUpsert) UpdateMessage() *LogEntryUpsert {
	u.SetExcluded(logentry.FieldMessage)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.LogEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(logentry.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LogEntryUpsertOne) UpdateNewValues() *LogEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(logentry.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LogEntry.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LogEntryUpsertOne) Ignore() *LogEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LogEntryUpsertOne) DoNothing() *LogEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LogEntryCreate.OnConflict
// documentation for more info.
func (u *LogEntryUpsertOne) Update(set func(*LogEntryUpsert)) *LogEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LogEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetDateTime sets the "date_time" field.
func (u *LogEntryUpsertOne) SetDateTime(v time.Time) *LogEntryUpsertOne {
	return u.Update(func(s *LogEntryUpsert) {
		s.SetDateTime(v)
	})
}

// UpdateDateTime sets the "date_time" field to the value that was provided on create.
func (u *LogEntryUpsertOne) UpdateDateTime() *LogEntryUpsertOne {
	return u.Update(func(s *LogEntryUpsert) {
		s.UpdateDateTime()
	})
}

// SetLevel sets the "level" field.
func (u *LogEntryUpsertOne) SetLevel(v string) *LogEntryUpsertOne {
	return u.Update(func(s *LogEntryUpsert) {
		s.SetLevel(v)
	})
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *LogEntryUpsertOne) UpdateLevel() *LogEntryUpsertOne {
	return u.Update(func(s *LogEntryUpsert) {
		s.UpdateLevel()
	})
}

// SetMessage sets the "message" field.
func (u *LogEntryUpsertOne) SetMessage(v string) *LogEntryUpsertOne {
	return u.Update(func(s *LogEntryUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *LogEntryUpsertOne) UpdateMessage() *LogEntryUpsertOne {
	return u.Update(func(s *LogEntryUpsert) {
		s.UpdateMessage()
	})
}

// Exec executes the query.
func (u *LogEntryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LogEntryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LogEntryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LogEntryUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LogEntryUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LogEntryCreateBulk is the builder for creating many LogEntry entities in bulk.
type LogEntryCreateBulk struct {
	config
	err      error
	builders []*LogEntryCreate
	conflict []sql.ConflictOption
}

// Save creates the LogEntry entities in the database.
func (_c *LogEntryCreateBulk) Save(ctx context.Context) ([]*LogEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LogEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LogEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LogEntryCreateBulk) SaveX(ctx context.Context) []*LogEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LogEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LogEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LogEntry.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LogEntryUpsert) {
//			SetDateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *LogEntryCreateBulk) OnConflict(opts ...sql.ConflictOption) *LogEntryUpsertBulk {
	_c.conflict = opts
	return &LogEntryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LogEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LogEntryCreateBulk) OnConflictColumns(columns ...string) *LogEntryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LogEntryUpsertBulk{
		create: _c,
	}
}

// LogEntryUpsertBulk is the builder for "upsert"-ing
// a bulk of LogEntry nodes.
type LogEntryUpsertBulk struct {
	create *LogEntryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LogEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(logentry.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LogEntryUpsertBulk) UpdateNewValues() *LogEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(logentry.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LogEntry.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LogEntryUpsertBulk) Ignore() *LogEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LogEntryUpsertBulk) DoNothing() *LogEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LogEntryCreateBulk.OnConflict
// documentation for more info.
func (u *LogEntryUpsertBulk) Update(set func(*LogEntryUpsert)) *LogEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LogEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetDateTime sets the "date_time" field.
func (u *LogEntryUpsertBulk) SetDateTime(v time.Time) *LogEntryUpsertBulk {
	return u.Update(func(s *LogEntryUpsert) {
		s.SetDateTime(v)
	})
}

// UpdateDateTime sets the "date_time" field to the value that was provided on create.
func (u *LogEntryUpsertBulk) UpdateDateTime() *LogEntryUpsertBulk {
	return u.Update(func(s *LogEntryUpsert) {
		s.UpdateDateTime()
	})
}

// SetLevel sets the "level" field.
func (u *LogEntryUpsertBulk) SetLevel(v string) *LogEntryUpsertBulk {
	return u.Update(func(s *LogEntryUpsert) {
		s.SetLevel(v)
	})
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *LogEntryUpsertBulk) UpdateLevel() *LogEntryUpsertBulk {
	return u.Update(func(s *LogEntryUpsert) {
		s.UpdateLevel()
	})
}

// SetMessage sets the "message" field.
func (u *LogEntryUpsertBulk) SetMessage(v string) *LogEntryUpsertBulk {
	return u.Update(func(s *LogEntryUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *LogEntryUpsertBulk) UpdateMessage() *LogEntryUpsertBulk {
	return u.Update(func(s *LogEntryUpsert) {
		s.UpdateMessage()
	})
}

// Exec executes the query.
func (u *LogEntryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LogEntryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LogEntryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LogEntryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
