// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/USA-RedDragon/rdio-scanner/server/ent/apikey"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/dirwatch"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/downstream"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/schema"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/system"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyFields := schema.Apikey{}.Fields()
	_ = apikeyFields
	// apikeyDescDisabled is the schema descriptor for disabled field.
	apikeyDescDisabled := apikeyFields[1].Descriptor()
	// apikey.DefaultDisabled holds the default value on creation for the disabled field.
	apikey.DefaultDisabled = apikeyDescDisabled.Default.(bool)
	dirwatchFields := schema.Dirwatch{}.Fields()
	_ = dirwatchFields
	// dirwatchDescDelay is the schema descriptor for delay field.
	dirwatchDescDelay := dirwatchFields[1].Descriptor()
	// dirwatch.DefaultDelay holds the default value on creation for the delay field.
	dirwatch.DefaultDelay = dirwatchDescDelay.Default.(int)
	// dirwatchDescDeleteAfter is the schema descriptor for delete_after field.
	dirwatchDescDeleteAfter := dirwatchFields[2].Descriptor()
	// dirwatch.DefaultDeleteAfter holds the default value on creation for the delete_after field.
	dirwatch.DefaultDeleteAfter = dirwatchDescDeleteAfter.Default.(bool)
	// dirwatchDescDisabled is the schema descriptor for disabled field.
	dirwatchDescDisabled := dirwatchFields[4].Descriptor()
	// dirwatch.DefaultDisabled holds the default value on creation for the disabled field.
	dirwatch.DefaultDisabled = dirwatchDescDisabled.Default.(bool)
	// dirwatchDescUsePolling is the schema descriptor for use_polling field.
	dirwatchDescUsePolling := dirwatchFields[12].Descriptor()
	// dirwatch.DefaultUsePolling holds the default value on creation for the use_polling field.
	dirwatch.DefaultUsePolling = dirwatchDescUsePolling.Default.(bool)
	downstreamFields := schema.Downstream{}.Fields()
	_ = downstreamFields
	// downstreamDescDisabled is the schema descriptor for disabled field.
	downstreamDescDisabled := downstreamFields[2].Descriptor()
	// downstream.DefaultDisabled holds the default value on creation for the disabled field.
	downstream.DefaultDisabled = downstreamDescDisabled.Default.(bool)
	systemFields := schema.System{}.Fields()
	_ = systemFields
	// systemDescAutoPopulate is the schema descriptor for auto_populate field.
	systemDescAutoPopulate := systemFields[1].Descriptor()
	// system.DefaultAutoPopulate holds the default value on creation for the auto_populate field.
	system.DefaultAutoPopulate = systemDescAutoPopulate.Default.(bool)
}
