// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/system"
)

// SystemCreate is the builder for creating a System entity.
type SystemCreate struct {
	config
	mutation *SystemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAutoPopulate sets the "auto_populate" field.
func (_c *SystemCreate) SetAutoPopulate(v bool) *SystemCreate {
	_c.mutation.SetAutoPopulate(v)
	return _c
}

// SetNillableAutoPopulate sets the "auto_populate" field if the given value is not nil.
func (_c *SystemCreate) SetNillableAutoPopulate(v *bool) *SystemCreate {
	if v != nil {
		_c.SetAutoPopulate(*v)
	}
	return _c
}

// SetBlacklists sets the "blacklists" field.
func (_c *SystemCreate) SetBlacklists(v string) *SystemCreate {
	_c.mutation.SetBlacklists(v)
	return _c
}

// SetSystemID sets the "system_id" field.
func (_c *SystemCreate) SetSystemID(v int) *SystemCreate {
	_c.mutation.SetSystemID(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *SystemCreate) SetLabel(v string) *SystemCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetLed sets the "led" field.
func (_c *SystemCreate) SetLed(v string) *SystemCreate {
	_c.mutation.SetLed(v)
	return _c
}

// SetNillableLed sets the "led" field if the given value is not nil.
func (_c *SystemCreate) SetNillableLed(v *string) *SystemCreate {
	if v != nil {
		_c.SetLed(*v)
	}
	return _c
}

// SetOrder sets the "order" field.
func (_c *SystemCreate) SetOrder(v int) *SystemCreate {
	_c.mutation.SetOrder(v)
	return _c
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_c *SystemCreate) SetNillableOrder(v *int) *SystemCreate {
	if v != nil {
		_c.SetOrder(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SystemCreate) SetID(v int) *SystemCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SystemMutation object of the builder.
func (_c *SystemCreate) Mutation() *SystemMutation {
	return _c.mutation
}

// Save creates the System in the database.
func (_c *SystemCreate) Save(ctx context.Context) (*System, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SystemCreate) SaveX(ctx context.Context) *System {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SystemCreate) defaults() {
	if _, ok := _c.mutation.AutoPopulate(); !ok {
		v := system.DefaultAutoPopulate
		_c.mutation.SetAutoPopulate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SystemCreate) check() error {
	if _, ok := _c.mutation.Blacklists(); !ok {
		return &ValidationError{Name: "blacklists", err: errors.New(`ent: missing required field "System.blacklists"`)}
	}
	if _, ok := _c.mutation.SystemID(); !ok {
		return &ValidationError{Name: "system_id", err: errors.New(`ent: missing required field "System.system_id"`)}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "System.label"`)}
	}
	return nil
}

func (_c *SystemCreate) sqlSave(ctx context.Context) (*System, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SystemCreate) createSpec() (*System, *sqlgraph.CreateSpec) {
	var (
		_node = &System{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(system.Table, sqlgraph.NewFieldSpec(system.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AutoPopulate(); ok {
		_spec.SetField(system.FieldAutoPopulate, field.TypeBool, value)
		_node.AutoPopulate = &value
	}
	if value, ok := _c.mutation.Blacklists(); ok {
		_spec.SetField(system.FieldBlacklists, field.TypeString, value)
		_node.Blacklists = value
	}
	if value, ok := _c.mutation.SystemID(); ok {
		_spec.SetField(system.FieldSystemID, field.TypeInt, value)
		_node.SystemID = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(system.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Led(); ok {
		_spec.SetField(system.FieldLed, field.TypeString, value)
		_node.Led = &value
	}
	if value, ok := _c.mutation.Order(); ok {
		_spec.SetField(system.FieldOrder, field.TypeInt, value)
		_node.Order = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.System.Create().
//		SetAutoPopulate(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SystemUpsert) {
//			SetAutoPopulate(v+v).
//		}).
//		Exec(ctx)
func (_c *SystemCreate) OnConflict(opts ...sql.ConflictOption) *SystemUpsertOne {
	_c.conflict = opts
	return &SystemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.System.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SystemCreate) OnConflictColumns(columns ...string) *SystemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SystemUpsertOne{
		create: _c,
	}
}

type (
	// SystemUpsertOne is the builder for "upsert"-ing
	//  one System node.
	SystemUpsertOne struct {
		create *SystemCreate
	}

	// SystemUpsert is the "OnConflict" setter.
	SystemUpsert struct {
		*sql.UpdateSet
	}
)

// SetAutoPopulate sets the "auto_populate" field.
func (u *SystemUpsert) SetAutoPopulate(v bool) *SystemUpsert {
	u.Set(system.FieldAutoPopulate, v)
	return u
}

// UpdateAutoPopulate sets the "auto_populate" field to the value that was provided on create.
func (u *SystemUpsert) UpdateAutoPopulate() *SystemUpsert {
	u.SetExcluded(system.FieldAutoPopulate)
	return u
}

// ClearAutoPopulate clears the value of the "auto_populate" field.
func (u *SystemUpsert) ClearAutoPopulate() *SystemUpsert {
	u.SetNull(system.FieldAutoPopulate)
	return u
}

// SetBlacklists sets the "blacklists" field.
func (u *SystemUpsert) SetBlacklists(v string) *SystemUpsert {
	u.Set(system.FieldBlacklists, v)
	return u
}

// UpdateBlacklists sets the "blacklists" field to the value that was provided on create.
func (u *SystemUpsert) UpdateBlacklists() *SystemUpsert {
	u.SetExcluded(system.FieldBlacklists)
	return u
}

// SetSystemID sets the "system_id" field.
func (u *SystemUpsert) SetSystemID(v int) *SystemUpsert {
	u.Set(system.FieldSystemID, v)
	return u
}

// UpdateSystemID sets the "system_id" field to the value that was provided on create.
func (u *SystemUpsert) UpdateSystemID() *SystemUpsert {
	u.SetExcluded(system.FieldSystemID)
	return u
}

// AddSystemID adds v to the "system_id" field.
func (u *SystemUpsert) AddSystemID(v int) *SystemUpsert {
	u.Add(system.FieldSystemID, v)
	return u
}

// SetLabel sets the "label" field.
func (u *SystemUpsert) SetLabel(v string) *SystemUpsert {
	u.Set(system.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *SystemUpsert) UpdateLabel() *SystemUpsert {
	u.SetExcluded(system.FieldLabel)
	return u
}

// SetLed sets the "led" field.
func (u *SystemUpsert) SetLed(v string) *SystemUpsert {
	u.Set(system.FieldLed, v)
	return u
}

// UpdateLed sets the "led" field to the value that was provided on create.
func (u *SystemUpsert) UpdateLed() *SystemUpsert {
	u.SetExcluded(system.FieldLed)
	return u
}

// ClearLed clears the value of the "led" field.
func (u *SystemUpsert) ClearLed() *SystemUpsert {
	u.SetNull(system.FieldLed)
	return u
}

// SetOrder sets the "order" field.
func (u *SystemUpsert) SetOrder(v int) *SystemUpsert {
	u.Set(system.FieldOrder, v)
	return u
}

// UpdateOrder sets the "order" field to the value that was provided on create.
func (u *SystemUpsert) UpdateOrder() *SystemUpsert {
	u.SetExcluded(system.FieldOrder)
	return u
}

// AddOrder adds v to the "order" field.
func (u *SystemUpsert) AddOrder(v int) *SystemUpsert {
	u.Add(system.FieldOrder, v)
	return u
}

// ClearOrder clears the value of the "order" field.
func (u *SystemUpsert) ClearOrder() *SystemUpsert {
	u.SetNull(system.FieldOrder)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.System.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(system.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SystemUpsertOne) UpdateNewValues() *SystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(system.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.System.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SystemUpsertOne) Ignore() *SystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SystemUpsertOne) DoNothing() *SystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SystemCreate.OnConflict
// documentation for more info.
func (u *SystemUpsertOne) Update(set func(*SystemUpsert)) *SystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SystemUpsert{UpdateSet: update})
	}))
	return u
}

// SetAutoPopulate sets the "auto_populate" field.
func (u *SystemUpsertOne) SetAutoPopulate(v bool) *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.SetAutoPopulate(v)
	})
}

// UpdateAutoPopulate sets the "auto_populate" field to the value that was provided on create.
func (u *SystemUpsertOne) UpdateAutoPopulate() *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateAutoPopulate()
	})
}

// ClearAutoPopulate clears the value of the "auto_populate" field.
func (u *SystemUpsertOne) ClearAutoPopulate() *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.ClearAutoPopulate()
	})
}

// SetBlacklists sets the "blacklists" field.
func (u *SystemUpsertOne) SetBlacklists(v string) *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.SetBlacklists(v)
	})
}

// UpdateBlacklists sets the "blacklists" field to the value that was provided on create.
func (u *SystemUpsertOne) UpdateBlacklists() *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateBlacklists()
	})
}

// SetSystemID sets the "system_id" field.
func (u *SystemUpsertOne) SetSystemID(v int) *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.SetSystemID(v)
	})
}

// AddSystemID adds v to the "system_id" field.
func (u *SystemUpsertOne) AddSystemID(v int) *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.AddSystemID(v)
	})
}

// UpdateSystemID sets the "system_id" field to the value that was provided on create.
func (u *SystemUpsertOne) UpdateSystemID() *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateSystemID()
	})
}

// SetLabel sets the "label" field.
func (u *SystemUpsertOne) SetLabel(v string) *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *SystemUpsertOne) UpdateLabel() *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateLabel()
	})
}

// SetLed sets the "led" field.
func (u *SystemUpsertOne) SetLed(v string) *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.SetLed(v)
	})
}

// UpdateLed sets the "led" field to the value that was provided on create.
func (u *SystemUpsertOne) UpdateLed() *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateLed()
	})
}

// ClearLed clears the value of the "led" field.
func (u *SystemUpsertOne) ClearLed() *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.ClearLed()
	})
}

// SetOrder sets the "order" field.
func (u *SystemUpsertOne) SetOrder(v int) *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.SetOrder(v)
	})
}

// AddOrder adds v to the "order" field.
func (u *SystemUpsertOne) AddOrder(v int) *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.AddOrder(v)
	})
}

// UpdateOrder sets the "order" field to the value that was provided on create.
func (u *SystemUpsertOne) UpdateOrder() *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateOrder()
	})
}

// ClearOrder clears the value of the "order" field.
func (u *SystemUpsertOne) ClearOrder() *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.ClearOrder()
	})
}

// Exec executes the query.
func (u *SystemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SystemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SystemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SystemUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SystemUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SystemCreateBulk is the builder for creating many System entities in bulk.
type SystemCreateBulk struct {
	config
	err      error
	builders []*SystemCreate
	conflict []sql.ConflictOption
}

// Save creates the System entities in the database.
func (_c *SystemCreateBulk) Save(ctx context.Context) ([]*System, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*System, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SystemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SystemCreateBulk) SaveX(ctx context.Context) []*System {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.System.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SystemUpsert) {
//			SetAutoPopulate(v+v).
//		}).
//		Exec(ctx)
func (_c *SystemCreateBulk) OnConflict(opts ...sql.ConflictOption) *SystemUpsertBulk {
	_c.conflict = opts
	return &SystemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.System.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SystemCreateBulk) OnConflictColumns(columns ...string) *SystemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SystemUpsertBulk{
		create: _c,
	}
}

// SystemUpsertBulk is the builder for "upsert"-ing
// a bulk of System nodes.
type SystemUpsertBulk struct {
	create *SystemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.System.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(system.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SystemUpsertBulk) UpdateNewValues() *SystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(system.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.System.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SystemUpsertBulk) Ignore() *SystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SystemUpsertBulk) DoNothing() *SystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SystemCreateBulk.OnConflict
// documentation for more info.
func (u *SystemUpsertBulk) Update(set func(*SystemUpsert)) *SystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SystemUpsert{UpdateSet: update})
	}))
	return u
}

// SetAutoPopulate sets the "auto_populate" field.
func (u *SystemUpsertBulk) SetAutoPopulate(v bool) *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.SetAutoPopulate(v)
	})
}

// UpdateAutoPopulate sets the "auto_populate" field to the value that was provided on create.
func (u *SystemUpsertBulk) UpdateAutoPopulate() *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateAutoPopulate()
	})
}

// ClearAutoPopulate clears the value of the "auto_populate" field.
func (u *SystemUpsertBulk) ClearAutoPopulate() *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.ClearAutoPopulate()
	})
}

// SetBlacklists sets the "blacklists" field.
func (u *SystemUpsertBulk) SetBlacklists(v string) *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.SetBlacklists(v)
	})
}

// UpdateBlacklists sets the "blacklists" field to the value that was provided on create.
func (u *SystemUpsertBulk) UpdateBlacklists() *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateBlacklists()
	})
}

// SetSystemID sets the "system_id" field.
func (u *SystemUpsertBulk) SetSystemID(v int) *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.SetSystemID(v)
	})
}

// AddSystemID adds v to the "system_id" field.
func (u *SystemUpsertBulk) AddSystemID(v int) *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.AddSystemID(v)
	})
}

// UpdateSystemID sets the "system_id" field to the value that was provided on create.
func (u *SystemUpsertBulk) UpdateSystemID() *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateSystemID()
	})
}

// SetLabel sets the "label" field.
func (u *SystemUpsertBulk) SetLabel(v string) *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *SystemUpsertBulk) UpdateLabel() *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateLabel()
	})
}

// SetLed sets the "led" field.
func (u *SystemUpsertBulk) SetLed(v string) *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.SetLed(v)
	})
}

// UpdateLed sets the "led" field to the value that was provided on create.
func (u *SystemUpsertBulk) UpdateLed() *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateLed()
	})
}

// ClearLed clears the value of the "led" field.
func (u *SystemUpsertBulk) ClearLed() *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.ClearLed()
	})
}

// SetOrder sets the "order" field.
func (u *SystemUpsertBulk) SetOrder(v int) *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.SetOrder(v)
	})
}

// AddOrder adds v to the "order" field.
func (u *SystemUpsertBulk) AddOrder(v int) *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.AddOrder(v)
	})
}

// UpdateOrder sets the "order" field to the value that was provided on create.
func (u *SystemUpsertBulk) UpdateOrder() *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateOrder()
	})
}

// ClearOrder clears the value of the "order" field.
func (u *SystemUpsertBulk) ClearOrder() *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.ClearOrder()
	})
}

// Exec executes the query.
func (u *SystemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SystemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SystemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SystemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
