// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/system"
)

// System is the model entity for the System schema.
type System struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AutoPopulate holds the value of the "auto_populate" field.
	AutoPopulate *bool `json:"auto_populate,omitempty"`
	// Blacklists holds the value of the "blacklists" field.
	Blacklists string `json:"blacklists,omitempty"`
	// SystemID holds the value of the "system_id" field.
	SystemID int `json:"system_id,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// Led holds the value of the "led" field.
	Led *string `json:"led,omitempty"`
	// Order holds the value of the "order" field.
	Order        *int `json:"order,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*System) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case system.FieldAutoPopulate:
			values[i] = new(sql.NullBool)
		case system.FieldID, system.FieldSystemID, system.FieldOrder:
			values[i] = new(sql.NullInt64)
		case system.FieldBlacklists, system.FieldLabel, system.FieldLed:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the System fields.
func (_m *System) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case system.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case system.FieldAutoPopulate:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_populate", values[i])
			} else if value.Valid {
				_m.AutoPopulate = new(bool)
				*_m.AutoPopulate = value.Bool
			}
		case system.FieldBlacklists:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field blacklists", values[i])
			} else if value.Valid {
				_m.Blacklists = value.String
			}
		case system.FieldSystemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field system_id", values[i])
			} else if value.Valid {
				_m.SystemID = int(value.Int64)
			}
		case system.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case system.FieldLed:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field led", values[i])
			} else if value.Valid {
				_m.Led = new(string)
				*_m.Led = value.String
			}
		case system.FieldOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order", values[i])
			} else if value.Valid {
				_m.Order = new(int)
				*_m.Order = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the System.
// This includes values selected through modifiers, order, etc.
func (_m *System) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this System.
// Note that you need to call System.Unwrap() before calling this method if this System
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *System) Update() *SystemUpdateOne {
	return NewSystemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the System entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *System) Unwrap() *System {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: System is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *System) String() string {
	var builder strings.Builder
	builder.WriteString("System(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.AutoPopulate; v != nil {
		builder.WriteString("auto_populate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("blacklists=")
	builder.WriteString(_m.Blacklists)
	builder.WriteString(", ")
	builder.WriteString("system_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SystemID))
	builder.WriteString(", ")
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	if v := _m.Led; v != nil {
		builder.WriteString("led=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Order; v != nil {
		builder.WriteString("order=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Systems is a parsable slice of System.
type Systems []*System
