// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/predicate"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/system"
)

// SystemUpdate is the builder for updating System entities.
type SystemUpdate struct {
	config
	hooks    []Hook
	mutation *SystemMutation
}

// Where appends a list predicates to the SystemUpdate builder.
func (_u *SystemUpdate) Where(ps ...predicate.System) *SystemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAutoPopulate sets the "auto_populate" field.
func (_u *SystemUpdate) SetAutoPopulate(v bool) *SystemUpdate {
	_u.mutation.SetAutoPopulate(v)
	return _u
}

// SetNillableAutoPopulate sets the "auto_populate" field if the given value is not nil.
func (_u *SystemUpdate) SetNillableAutoPopulate(v *bool) *SystemUpdate {
	if v != nil {
		_u.SetAutoPopulate(*v)
	}
	return _u
}

// ClearAutoPopulate clears the value of the "auto_populate" field.
func (_u *SystemUpdate) ClearAutoPopulate() *SystemUpdate {
	_u.mutation.ClearAutoPopulate()
	return _u
}

// SetBlacklists sets the "blacklists" field.
func (_u *SystemUpdate) SetBlacklists(v string) *SystemUpdate {
	_u.mutation.SetBlacklists(v)
	return _u
}

// SetNillableBlacklists sets the "blacklists" field if the given value is not nil.
func (_u *SystemUpdate) SetNillableBlacklists(v *string) *SystemUpdate {
	if v != nil {
		_u.SetBlacklists(*v)
	}
	return _u
}

// SetSystemID sets the "system_id" field.
func (_u *SystemUpdate) SetSystemID(v int) *SystemUpdate {
	_u.mutation.ResetSystemID()
	_u.mutation.SetSystemID(v)
	return _u
}

// SetNillableSystemID sets the "system_id" field if the given value is not nil.
func (_u *SystemUpdate) SetNillableSystemID(v *int) *SystemUpdate {
	if v != nil {
		_u.SetSystemID(*v)
	}
	return _u
}

// AddSystemID adds value to the "system_id" field.
func (_u *SystemUpdate) AddSystemID(v int) *SystemUpdate {
	_u.mutation.AddSystemID(v)
	return _u
}

// SetLabel sets the "label" field.
func (_u *SystemUpdate) SetLabel(v string) *SystemUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *SystemUpdate) SetNillableLabel(v *string) *SystemUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetLed sets the "led" field.
func (_u *SystemUpdate) SetLed(v string) *SystemUpdate {
	_u.mutation.SetLed(v)
	return _u
}

// SetNillableLed sets the "led" field if the given value is not nil.
func (_u *SystemUpdate) SetNillableLed(v *string) *SystemUpdate {
	if v != nil {
		_u.SetLed(*v)
	}
	return _u
}

// ClearLed clears the value of the "led" field.
func (_u *SystemUpdate) ClearLed() *SystemUpdate {
	_u.mutation.ClearLed()
	return _u
}

// SetOrder sets the "order" field.
func (_u *SystemUpdate) SetOrder(v int) *SystemUpdate {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *SystemUpdate) SetNillableOrder(v *int) *SystemUpdate {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *SystemUpdate) AddOrder(v int) *SystemUpdate {
	_u.mutation.AddOrder(v)
	return _u
}

// ClearOrder clears the value of the "order" field.
func (_u *SystemUpdate) ClearOrder() *SystemUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// Mutation returns the SystemMutation object of the builder.
func (_u *SystemUpdate) Mutation() *SystemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SystemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(system.Table, system.Columns, sqlgraph.NewFieldSpec(system.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AutoPopulate(); ok {
		_spec.SetField(system.FieldAutoPopulate, field.TypeBool, value)
	}
	if _u.mutation.AutoPopulateCleared() {
		_spec.ClearField(system.FieldAutoPopulate, field.TypeBool)
	}
	if value, ok := _u.mutation.Blacklists(); ok {
		_spec.SetField(system.FieldBlacklists, field.TypeString, value)
	}
	if value, ok := _u.mutation.SystemID(); ok {
		_spec.SetField(system.FieldSystemID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSystemID(); ok {
		_spec.AddField(system.FieldSystemID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(system.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Led(); ok {
		_spec.SetField(system.FieldLed, field.TypeString, value)
	}
	if _u.mutation.LedCleared() {
		_spec.ClearField(system.FieldLed, field.TypeString)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(system.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(system.FieldOrder, field.TypeInt, value)
	}
	if _u.mutation.OrderCleared() {
		_spec.ClearField(system.FieldOrder, field.TypeInt)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{system.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemUpdateOne is the builder for updating a single System entity.
type SystemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemMutation
}

// SetAutoPopulate sets the "auto_populate" field.
func (_u *SystemUpdateOne) SetAutoPopulate(v bool) *SystemUpdateOne {
	_u.mutation.SetAutoPopulate(v)
	return _u
}

// SetNillableAutoPopulate sets the "auto_populate" field if the given value is not nil.
func (_u *SystemUpdateOne) SetNillableAutoPopulate(v *bool) *SystemUpdateOne {
	if v != nil {
		_u.SetAutoPopulate(*v)
	}
	return _u
}

// ClearAutoPopulate clears the value of the "auto_populate" field.
func (_u *SystemUpdateOne) ClearAutoPopulate() *SystemUpdateOne {
	_u.mutation.ClearAutoPopulate()
	return _u
}

// SetBlacklists sets the "blacklists" field.
func (_u *SystemUpdateOne) SetBlacklists(v string) *SystemUpdateOne {
	_u.mutation.SetBlacklists(v)
	return _u
}

// SetNillableBlacklists sets the "blacklists" field if the given value is not nil.
func (_u *SystemUpdateOne) SetNillableBlacklists(v *string) *SystemUpdateOne {
	if v != nil {
		_u.SetBlacklists(*v)
	}
	return _u
}

// SetSystemID sets the "system_id" field.
func (_u *SystemUpdateOne) SetSystemID(v int) *SystemUpdateOne {
	_u.mutation.ResetSystemID()
	_u.mutation.SetSystemID(v)
	return _u
}

// SetNillableSystemID sets the "system_id" field if the given value is not nil.
func (_u *SystemUpdateOne) SetNillableSystemID(v *int) *SystemUpdateOne {
	if v != nil {
		_u.SetSystemID(*v)
	}
	return _u
}

// AddSystemID adds value to the "system_id" field.
func (_u *SystemUpdateOne) AddSystemID(v int) *SystemUpdateOne {
	_u.mutation.AddSystemID(v)
	return _u
}

// SetLabel sets the "label" field.
func (_u *SystemUpdateOne) SetLabel(v string) *SystemUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *SystemUpdateOne) SetNillableLabel(v *string) *SystemUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetLed sets the "led" field.
func (_u *SystemUpdateOne) SetLed(v string) *SystemUpdateOne {
	_u.mutation.SetLed(v)
	return _u
}

// SetNillableLed sets the "led" field if the given value is not nil.
func (_u *SystemUpdateOne) SetNillableLed(v *string) *SystemUpdateOne {
	if v != nil {
		_u.SetLed(*v)
	}
	return _u
}

// ClearLed clears the value of the "led" field.
func (_u *SystemUpdateOne) ClearLed() *SystemUpdateOne {
	_u.mutation.ClearLed()
	return _u
}

// SetOrder sets the "order" field.
func (_u *SystemUpdateOne) SetOrder(v int) *SystemUpdateOne {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *SystemUpdateOne) SetNillableOrder(v *int) *SystemUpdateOne {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *SystemUpdateOne) AddOrder(v int) *SystemUpdateOne {
	_u.mutation.AddOrder(v)
	return _u
}

// ClearOrder clears the value of the "order" field.
func (_u *SystemUpdateOne) ClearOrder() *SystemUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// Mutation returns the SystemMutation object of the builder.
func (_u *SystemUpdateOne) Mutation() *SystemMutation {
	return _u.mutation
}

// Where appends a list predicates to the SystemUpdate builder.
func (_u *SystemUpdateOne) Where(ps ...predicate.System) *SystemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemUpdateOne) Select(field string, fields ...string) *SystemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated System entity.
func (_u *SystemUpdateOne) Save(ctx context.Context) (*System, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemUpdateOne) SaveX(ctx context.Context) *System {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SystemUpdateOne) sqlSave(ctx context.Context) (_node *System, err error) {
	_spec := sqlgraph.NewUpdateSpec(system.Table, system.Columns, sqlgraph.NewFieldSpec(system.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "System.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, system.FieldID)
		for _, f := range fields {
			if !system.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != system.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AutoPopulate(); ok {
		_spec.SetField(system.FieldAutoPopulate, field.TypeBool, value)
	}
	if _u.mutation.AutoPopulateCleared() {
		_spec.ClearField(system.FieldAutoPopulate, field.TypeBool)
	}
	if value, ok := _u.mutation.Blacklists(); ok {
		_spec.SetField(system.FieldBlacklists, field.TypeString, value)
	}
	if value, ok := _u.mutation.SystemID(); ok {
		_spec.SetField(system.FieldSystemID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSystemID(); ok {
		_spec.AddField(system.FieldSystemID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(system.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Led(); ok {
		_spec.SetField(system.FieldLed, field.TypeString, value)
	}
	if _u.mutation.LedCleared() {
		_spec.ClearField(system.FieldLed, field.TypeString)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(system.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(system.FieldOrder, field.TypeInt, value)
	}
	if _u.mutation.OrderCleared() {
		_spec.ClearField(system.FieldOrder, field.TypeInt)
	}
	_node = &System{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{system.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
