// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/talkgroup"
)

// Talkgroup is the model entity for the Talkgroup schema.
type Talkgroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Frequency holds the value of the "frequency" field.
	Frequency *int `json:"frequency,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int `json:"group_id,omitempty"`
	// TalkgroupID holds the value of the "talkgroup_id" field.
	TalkgroupID int `json:"talkgroup_id,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// Led holds the value of the "led" field.
	Led *string `json:"led,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Order holds the value of the "order" field.
	Order *int `json:"order,omitempty"`
	// SystemID holds the value of the "system_id" field.
	SystemID int `json:"system_id,omitempty"`
	// TagID holds the value of the "tag_id" field.
	TagID        int `json:"tag_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Talkgroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case talkgroup.FieldID, talkgroup.FieldFrequency, talkgroup.FieldGroupID, talkgroup.FieldTalkgroupID, talkgroup.FieldOrder, talkgroup.FieldSystemID, talkgroup.FieldTagID:
			values[i] = new(sql.NullInt64)
		case talkgroup.FieldLabel, talkgroup.FieldLed, talkgroup.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Talkgroup fields.
func (_m *Talkgroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case talkgroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case talkgroup.FieldFrequency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field frequency", values[i])
			} else if value.Valid {
				_m.Frequency = new(int)
				*_m.Frequency = int(value.Int64)
			}
		case talkgroup.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = int(value.Int64)
			}
		case talkgroup.FieldTalkgroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field talkgroup_id", values[i])
			} else if value.Valid {
				_m.TalkgroupID = int(value.Int64)
			}
		case talkgroup.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case talkgroup.FieldLed:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field led", values[i])
			} else if value.Valid {
				_m.Led = new(string)
				*_m.Led = value.String
			}
		case talkgroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case talkgroup.FieldOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order", values[i])
			} else if value.Valid {
				_m.Order = new(int)
				*_m.Order = int(value.Int64)
			}
		case talkgroup.FieldSystemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field system_id", values[i])
			} else if value.Valid {
				_m.SystemID = int(value.Int64)
			}
		case talkgroup.FieldTagID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tag_id", values[i])
			} else if value.Valid {
				_m.TagID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Talkgroup.
// This includes values selected through modifiers, order, etc.
func (_m *Talkgroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Talkgroup.
// Note that you need to call Talkgroup.Unwrap() before calling this method if this Talkgroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Talkgroup) Update() *TalkgroupUpdateOne {
	return NewTalkgroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Talkgroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Talkgroup) Unwrap() *Talkgroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Talkgroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Talkgroup) String() string {
	var builder strings.Builder
	builder.WriteString("Talkgroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.Frequency; v != nil {
		builder.WriteString("frequency=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("talkgroup_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TalkgroupID))
	builder.WriteString(", ")
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	if v := _m.Led; v != nil {
		builder.WriteString("led=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Order; v != nil {
		builder.WriteString("order=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("system_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SystemID))
	builder.WriteString(", ")
	builder.WriteString("tag_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TagID))
	builder.WriteByte(')')
	return builder.String()
}

// Talkgroups is a parsable slice of Talkgroup.
type Talkgroups []*Talkgroup
