// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/unit"
)

// UnitCreate is the builder for creating a Unit entity.
type UnitCreate struct {
	config
	mutation *UnitMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUnitID sets the "unit_id" field.
func (_c *UnitCreate) SetUnitID(v int) *UnitCreate {
	_c.mutation.SetUnitID(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *UnitCreate) SetLabel(v string) *UnitCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetOrder sets the "order" field.
func (_c *UnitCreate) SetOrder(v int) *UnitCreate {
	_c.mutation.SetOrder(v)
	return _c
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_c *UnitCreate) SetNillableOrder(v *int) *UnitCreate {
	if v != nil {
		_c.SetOrder(*v)
	}
	return _c
}

// SetSystemID sets the "system_id" field.
func (_c *UnitCreate) SetSystemID(v int) *UnitCreate {
	_c.mutation.SetSystemID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *UnitCreate) SetID(v int) *UnitCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UnitMutation object of the builder.
func (_c *UnitCreate) Mutation() *UnitMutation {
	return _c.mutation
}

// Save creates the Unit in the database.
func (_c *UnitCreate) Save(ctx context.Context) (*Unit, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UnitCreate) SaveX(ctx context.Context) *Unit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnitCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnitCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UnitCreate) check() error {
	if _, ok := _c.mutation.UnitID(); !ok {
		return &ValidationError{Name: "unit_id", err: errors.New(`ent: missing required field "Unit.unit_id"`)}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "Unit.label"`)}
	}
	if _, ok := _c.mutation.SystemID(); !ok {
		return &ValidationError{Name: "system_id", err: errors.New(`ent: missing required field "Unit.system_id"`)}
	}
	return nil
}

func (_c *UnitCreate) sqlSave(ctx context.Context) (*Unit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UnitCreate) createSpec() (*Unit, *sqlgraph.CreateSpec) {
	var (
		_node = &Unit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(unit.Table, sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UnitID(); ok {
		_spec.SetField(unit.FieldUnitID, field.TypeInt, value)
		_node.UnitID = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(unit.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Order(); ok {
		_spec.SetField(unit.FieldOrder, field.TypeInt, value)
		_node.Order = &value
	}
	if value, ok := _c.mutation.SystemID(); ok {
		_spec.SetField(unit.FieldSystemID, field.TypeInt, value)
		_node.SystemID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Unit.Create().
//		SetUnitID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UnitUpsert) {
//			SetUnitID(v+v).
//		}).
//		Exec(ctx)
func (_c *UnitCreate) OnConflict(opts ...sql.ConflictOption) *UnitUpsertOne {
	_c.conflict = opts
	return &UnitUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UnitCreate) OnConflictColumns(columns ...string) *UnitUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UnitUpsertOne{
		create: _c,
	}
}

type (
	// UnitUpsertOne is the builder for "upsert"-ing
	//  one Unit node.
	UnitUpsertOne struct {
		create *UnitCreate
	}

	// UnitUpsert is the "OnConflict" setter.
	UnitUpsert struct {
		*sql.UpdateSet
	}
)

// SetUnitID sets the "unit_id" field.
func (u *UnitUpsert) SetUnitID(v int) *UnitUpsert {
	u.Set(unit.FieldUnitID, v)
	return u
}

// UpdateUnitID sets the "unit_id" field to the value that was provided on create.
func (u *UnitUpsert) UpdateUnitID() *UnitUpsert {
	u.SetExcluded(unit.FieldUnitID)
	return u
}

// AddUnitID adds v to the "unit_id" field.
func (u *UnitUpsert) AddUnitID(v int) *UnitUpsert {
	u.Add(unit.FieldUnitID, v)
	return u
}

// SetLabel sets the "label" field.
func (u *UnitUpsert) SetLabel(v string) *UnitUpsert {
	u.Set(unit.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *UnitUpsert) UpdateLabel() *UnitUpsert {
	u.SetExcluded(unit.FieldLabel)
	return u
}

// SetOrder sets the "order" field.
func (u *UnitUpsert) SetOrder(v int) *UnitUpsert {
	u.Set(unit.FieldOrder, v)
	return u
}

// UpdateOrder sets the "order" field to the value that was provided on create.
func (u *UnitUpsert) UpdateOrder() *UnitUpsert {
	u.SetExcluded(unit.FieldOrder)
	return u
}

// AddOrder adds v to the "order" field.
func (u *UnitUpsert) AddOrder(v int) *UnitUpsert {
	u.Add(unit.FieldOrder, v)
	return u
}

// ClearOrder clears the value of the "order" field.
func (u *UnitUpsert) ClearOrder() *UnitUpsert {
	u.SetNull(unit.FieldOrder)
	return u
}

// SetSystemID sets the "system_id" field.
func (u *UnitUpsert) SetSystemID(v int) *UnitUpsert {
	u.Set(unit.FieldSystemID, v)
	return u
}

// UpdateSystemID sets the "system_id" field to the value that was provided on create.
func (u *UnitUpsert) UpdateSystemID() *UnitUpsert {
	u.SetExcluded(unit.FieldSystemID)
	return u
}

// AddSystemID adds v to the "system_id" field.
func (u *UnitUpsert) AddSystemID(v int) *UnitUpsert {
	u.Add(unit.FieldSystemID, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(unit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UnitUpsertOne) UpdateNewValues() *UnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(unit.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Unit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UnitUpsertOne) Ignore() *UnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UnitUpsertOne) DoNothing() *UnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UnitCreate.OnConflict
// documentation for more info.
func (u *UnitUpsertOne) Update(set func(*UnitUpsert)) *UnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UnitUpsert{UpdateSet: update})
	}))
	return u
}

// SetUnitID sets the "unit_id" field.
func (u *UnitUpsertOne) SetUnitID(v int) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetUnitID(v)
	})
}

// AddUnitID adds v to the "unit_id" field.
func (u *UnitUpsertOne) AddUnitID(v int) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.AddUnitID(v)
	})
}

// UpdateUnitID sets the "unit_id" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateUnitID() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateUnitID()
	})
}

// SetLabel sets the "label" field.
func (u *UnitUpsertOne) SetLabel(v string) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateLabel() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateLabel()
	})
}

// SetOrder sets the "order" field.
func (u *UnitUpsertOne) SetOrder(v int) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetOrder(v)
	})
}

// AddOrder adds v to the "order" field.
func (u *UnitUpsertOne) AddOrder(v int) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.AddOrder(v)
	})
}

// UpdateOrder sets the "order" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateOrder() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateOrder()
	})
}

// ClearOrder clears the value of the "order" field.
func (u *UnitUpsertOne) ClearOrder() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.ClearOrder()
	})
}

// SetSystemID sets the "system_id" field.
func (u *UnitUpsertOne) SetSystemID(v int) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetSystemID(v)
	})
}

// AddSystemID adds v to the "system_id" field.
func (u *UnitUpsertOne) AddSystemID(v int) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.AddSystemID(v)
	})
}

// UpdateSystemID sets the "system_id" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateSystemID() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateSystemID()
	})
}

// Exec executes the query.
func (u *UnitUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UnitCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UnitUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UnitUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UnitUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UnitCreateBulk is the builder for creating many Unit entities in bulk.
type UnitCreateBulk struct {
	config
	err      error
	builders []*UnitCreate
	conflict []sql.ConflictOption
}

// Save creates the Unit entities in the database.
func (_c *UnitCreateBulk) Save(ctx context.Context) ([]*Unit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Unit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UnitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UnitCreateBulk) SaveX(ctx context.Context) []*Unit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnitCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnitCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Unit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UnitUpsert) {
//			SetUnitID(v+v).
//		}).
//		Exec(ctx)
func (_c *UnitCreateBulk) OnConflict(opts ...sql.ConflictOption) *UnitUpsertBulk {
	_c.conflict = opts
	return &UnitUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UnitCreateBulk) OnConflictColumns(columns ...string) *UnitUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UnitUpsertBulk{
		create: _c,
	}
}

// UnitUpsertBulk is the builder for "upsert"-ing
// a bulk of Unit nodes.
type UnitUpsertBulk struct {
	create *UnitCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(unit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UnitUpsertBulk) UpdateNewValues() *UnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(unit.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UnitUpsertBulk) Ignore() *UnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UnitUpsertBulk) DoNothing() *UnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UnitCreateBulk.OnConflict
// documentation for more info.
func (u *UnitUpsertBulk) Update(set func(*UnitUpsert)) *UnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UnitUpsert{UpdateSet: update})
	}))
	return u
}

// SetUnitID sets the "unit_id" field.
func (u *UnitUpsertBulk) SetUnitID(v int) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetUnitID(v)
	})
}

// AddUnitID adds v to the "unit_id" field.
func (u *UnitUpsertBulk) AddUnitID(v int) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.AddUnitID(v)
	})
}

// UpdateUnitID sets the "unit_id" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateUnitID() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateUnitID()
	})
}

// SetLabel sets the "label" field.
func (u *UnitUpsertBulk) SetLabel(v string) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateLabel() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateLabel()
	})
}

// SetOrder sets the "order" field.
func (u *UnitUpsertBulk) SetOrder(v int) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetOrder(v)
	})
}

// AddOrder adds v to the "order" field.
func (u *UnitUpsertBulk) AddOrder(v int) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.AddOrder(v)
	})
}

// UpdateOrder sets the "order" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateOrder() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateOrder()
	})
}

// ClearOrder clears the value of the "order" field.
func (u *UnitUpsertBulk) ClearOrder() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.ClearOrder()
	})
}

// SetSystemID sets the "system_id" field.
func (u *UnitUpsertBulk) SetSystemID(v int) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetSystemID(v)
	})
}

// AddSystemID adds v to the "system_id" field.
func (u *UnitUpsertBulk) AddSystemID(v int) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.AddSystemID(v)
	})
}

// UpdateSystemID sets the "system_id" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateSystemID() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateSystemID()
	})
}

// Exec executes the query.
func (u *UnitUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UnitCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UnitCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UnitUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
