// Code generated by ent, DO NOT EDIT.

package call

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the call type in the database.
	Label = "call"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAudio holds the string denoting the audio field in the database.
	FieldAudio = "audio"
	// FieldAudioName holds the string denoting the audio_name field in the database.
	FieldAudioName = "audioname"
	// FieldAudioType holds the string denoting the audio_type field in the database.
	FieldAudioType = "audiotype"
	// FieldDateTime holds the string denoting the date_time field in the database.
	FieldDateTime = "datetime"
	// FieldFrequencies holds the string denoting the frequencies field in the database.
	FieldFrequencies = "frequencies"
	// FieldFrequency holds the string denoting the frequency field in the database.
	FieldFrequency = "frequency"
	// FieldPatches holds the string denoting the patches field in the database.
	FieldPatches = "patches"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSources holds the string denoting the sources field in the database.
	FieldSources = "sources"
	// FieldSystem holds the string denoting the system field in the database.
	FieldSystem = "system"
	// FieldTalkgroup holds the string denoting the talkgroup field in the database.
	FieldTalkgroup = "talkgroup"
	// Table holds the table name of the call in the database.
	Table = "rdioscannercalls"
)

// Columns holds all SQL columns for call fields.
var Columns = []string{
	FieldID,
	FieldAudio,
	FieldAudioName,
	FieldAudioType,
	FieldDateTime,
	FieldFrequencies,
	FieldFrequency,
	FieldPatches,
	FieldSource,
	FieldSources,
	FieldSystem,
	FieldTalkgroup,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Call queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAudioName orders the results by the audio_name field.
func ByAudioName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAudioName, opts...).ToFunc()
}

// ByAudioType orders the results by the audio_type field.
func ByAudioType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAudioType, opts...).ToFunc()
}

// ByDateTime orders the results by the date_time field.
func ByDateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateTime, opts...).ToFunc()
}

// ByFrequencies orders the results by the frequencies field.
func ByFrequencies(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrequencies, opts...).ToFunc()
}

// ByFrequency orders the results by the frequency field.
func ByFrequency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrequency, opts...).ToFunc()
}

// ByPatches orders the results by the patches field.
func ByPatches(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPatches, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySources orders the results by the sources field.
func BySources(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSources, opts...).ToFunc()
}

// BySystem orders the results by the system field.
func BySystem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystem, opts...).ToFunc()
}

// ByTalkgroup orders the results by the talkgroup field.
func ByTalkgroup(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTalkgroup, opts...).ToFunc()
}
