// Code generated by ent, DO NOT EDIT.

package call

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Call {
	return predicate.Call(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Call {
	return predicate.Call(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Call {
	return predicate.Call(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Call {
	return predicate.Call(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Call {
	return predicate.Call(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Call {
	return predicate.Call(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Call {
	return predicate.Call(sql.FieldLTE(FieldID, id))
}

// Audio applies equality check predicate on the "audio" field. It's identical to AudioEQ.
func Audio(v []byte) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldAudio, v))
}

// AudioName applies equality check predicate on the "audio_name" field. It's identical to AudioNameEQ.
func AudioName(v string) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldAudioName, v))
}

// AudioType applies equality check predicate on the "audio_type" field. It's identical to AudioTypeEQ.
func AudioType(v string) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldAudioType, v))
}

// DateTime applies equality check predicate on the "date_time" field. It's identical to DateTimeEQ.
func DateTime(v time.Time) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldDateTime, v))
}

// Frequencies applies equality check predicate on the "frequencies" field. It's identical to FrequenciesEQ.
func Frequencies(v string) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldFrequencies, v))
}

// Frequency applies equality check predicate on the "frequency" field. It's identical to FrequencyEQ.
func Frequency(v int) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldFrequency, v))
}

// Patches applies equality check predicate on the "patches" field. It's identical to PatchesEQ.
func Patches(v string) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldPatches, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v int) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldSource, v))
}

// Sources applies equality check predicate on the "sources" field. It's identical to SourcesEQ.
func Sources(v string) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldSources, v))
}

// System applies equality check predicate on the "system" field. It's identical to SystemEQ.
func System(v int) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldSystem, v))
}

// Talkgroup applies equality check predicate on the "talkgroup" field. It's identical to TalkgroupEQ.
func Talkgroup(v int) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldTalkgroup, v))
}

// AudioEQ applies the EQ predicate on the "audio" field.
func AudioEQ(v []byte) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldAudio, v))
}

// AudioNEQ applies the NEQ predicate on the "audio" field.
func AudioNEQ(v []byte) predicate.Call {
	return predicate.Call(sql.FieldNEQ(FieldAudio, v))
}

// AudioIn applies the In predicate on the "audio" field.
func AudioIn(vs ...[]byte) predicate.Call {
	return predicate.Call(sql.FieldIn(FieldAudio, vs...))
}

// AudioNotIn applies the NotIn predicate on the "audio" field.
func AudioNotIn(vs ...[]byte) predicate.Call {
	return predicate.Call(sql.FieldNotIn(FieldAudio, vs...))
}

// AudioGT applies the GT predicate on the "audio" field.
func AudioGT(v []byte) predicate.Call {
	return predicate.Call(sql.FieldGT(FieldAudio, v))
}

// AudioGTE applies the GTE predicate on the "audio" field.
func AudioGTE(v []byte) predicate.Call {
	return predicate.Call(sql.FieldGTE(FieldAudio, v))
}

// AudioLT applies the LT predicate on the "audio" field.
func AudioLT(v []byte) predicate.Call {
	return predicate.Call(sql.FieldLT(FieldAudio, v))
}

// AudioLTE applies the LTE predicate on the "audio" field.
func AudioLTE(v []byte) predicate.Call {
	return predicate.Call(sql.FieldLTE(FieldAudio, v))
}

// AudioNameEQ applies the EQ predicate on the "audio_name" field.
func AudioNameEQ(v string) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldAudioName, v))
}

// AudioNameNEQ applies the NEQ predicate on the "audio_name" field.
func AudioNameNEQ(v string) predicate.Call {
	return predicate.Call(sql.FieldNEQ(FieldAudioName, v))
}

// AudioNameIn applies the In predicate on the "audio_name" field.
func AudioNameIn(vs ...string) predicate.Call {
	return predicate.Call(sql.FieldIn(FieldAudioName, vs...))
}

// AudioNameNotIn applies the NotIn predicate on the "audio_name" field.
func AudioNameNotIn(vs ...string) predicate.Call {
	return predicate.Call(sql.FieldNotIn(FieldAudioName, vs...))
}

// AudioNameGT applies the GT predicate on the "audio_name" field.
func AudioNameGT(v string) predicate.Call {
	return predicate.Call(sql.FieldGT(FieldAudioName, v))
}

// AudioNameGTE applies the GTE predicate on the "audio_name" field.
func AudioNameGTE(v string) predicate.Call {
	return predicate.Call(sql.FieldGTE(FieldAudioName, v))
}

// AudioNameLT applies the LT predicate on the "audio_name" field.
func AudioNameLT(v string) predicate.Call {
	return predicate.Call(sql.FieldLT(FieldAudioName, v))
}

// AudioNameLTE applies the LTE predicate on the "audio_name" field.
func AudioNameLTE(v string) predicate.Call {
	return predicate.Call(sql.FieldLTE(FieldAudioName, v))
}

// AudioNameContains applies the Contains predicate on the "audio_name" field.
func AudioNameContains(v string) predicate.Call {
	return predicate.Call(sql.FieldContains(FieldAudioName, v))
}

// AudioNameHasPrefix applies the HasPrefix predicate on the "audio_name" field.
func AudioNameHasPrefix(v string) predicate.Call {
	return predicate.Call(sql.FieldHasPrefix(FieldAudioName, v))
}

// AudioNameHasSuffix applies the HasSuffix predicate on the "audio_name" field.
func AudioNameHasSuffix(v string) predicate.Call {
	return predicate.Call(sql.FieldHasSuffix(FieldAudioName, v))
}

// AudioNameIsNil applies the IsNil predicate on the "audio_name" field.
func AudioNameIsNil() predicate.Call {
	return predicate.Call(sql.FieldIsNull(FieldAudioName))
}

// AudioNameNotNil applies the NotNil predicate on the "audio_name" field.
func AudioNameNotNil() predicate.Call {
	return predicate.Call(sql.FieldNotNull(FieldAudioName))
}

// AudioNameEqualFold applies the EqualFold predicate on the "audio_name" field.
func AudioNameEqualFold(v string) predicate.Call {
	return predicate.Call(sql.FieldEqualFold(FieldAudioName, v))
}

// AudioNameContainsFold applies the ContainsFold predicate on the "audio_name" field.
func AudioNameContainsFold(v string) predicate.Call {
	return predicate.Call(sql.FieldContainsFold(FieldAudioName, v))
}

// AudioTypeEQ applies the EQ predicate on the "audio_type" field.
func AudioTypeEQ(v string) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldAudioType, v))
}

// AudioTypeNEQ applies the NEQ predicate on the "audio_type" field.
func AudioTypeNEQ(v string) predicate.Call {
	return predicate.Call(sql.FieldNEQ(FieldAudioType, v))
}

// AudioTypeIn applies the In predicate on the "audio_type" field.
func AudioTypeIn(vs ...string) predicate.Call {
	return predicate.Call(sql.FieldIn(FieldAudioType, vs...))
}

// AudioTypeNotIn applies the NotIn predicate on the "audio_type" field.
func AudioTypeNotIn(vs ...string) predicate.Call {
	return predicate.Call(sql.FieldNotIn(FieldAudioType, vs...))
}

// AudioTypeGT applies the GT predicate on the "audio_type" field.
func AudioTypeGT(v string) predicate.Call {
	return predicate.Call(sql.FieldGT(FieldAudioType, v))
}

// AudioTypeGTE applies the GTE predicate on the "audio_type" field.
func AudioTypeGTE(v string) predicate.Call {
	return predicate.Call(sql.FieldGTE(FieldAudioType, v))
}

// AudioTypeLT applies the LT predicate on the "audio_type" field.
func AudioTypeLT(v string) predicate.Call {
	return predicate.Call(sql.FieldLT(FieldAudioType, v))
}

// AudioTypeLTE applies the LTE predicate on the "audio_type" field.
func AudioTypeLTE(v string) predicate.Call {
	return predicate.Call(sql.FieldLTE(FieldAudioType, v))
}

// AudioTypeContains applies the Contains predicate on the "audio_type" field.
func AudioTypeContains(v string) predicate.Call {
	return predicate.Call(sql.FieldContains(FieldAudioType, v))
}

// AudioTypeHasPrefix applies the HasPrefix predicate on the "audio_type" field.
func AudioTypeHasPrefix(v string) predicate.Call {
	return predicate.Call(sql.FieldHasPrefix(FieldAudioType, v))
}

// AudioTypeHasSuffix applies the HasSuffix predicate on the "audio_type" field.
func AudioTypeHasSuffix(v string) predicate.Call {
	return predicate.Call(sql.FieldHasSuffix(FieldAudioType, v))
}

// AudioTypeIsNil applies the IsNil predicate on the "audio_type" field.
func AudioTypeIsNil() predicate.Call {
	return predicate.Call(sql.FieldIsNull(FieldAudioType))
}

// AudioTypeNotNil applies the NotNil predicate on the "audio_type" field.
func AudioTypeNotNil() predicate.Call {
	return predicate.Call(sql.FieldNotNull(FieldAudioType))
}

// AudioTypeEqualFold applies the EqualFold predicate on the "audio_type" field.
func AudioTypeEqualFold(v string) predicate.Call {
	return predicate.Call(sql.FieldEqualFold(FieldAudioType, v))
}

// AudioTypeContainsFold applies the ContainsFold predicate on the "audio_type" field.
func AudioTypeContainsFold(v string) predicate.Call {
	return predicate.Call(sql.FieldContainsFold(FieldAudioType, v))
}

// DateTimeEQ applies the EQ predicate on the "date_time" field.
func DateTimeEQ(v time.Time) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldDateTime, v))
}

// DateTimeNEQ applies the NEQ predicate on the "date_time" field.
func DateTimeNEQ(v time.Time) predicate.Call {
	return predicate.Call(sql.FieldNEQ(FieldDateTime, v))
}

// DateTimeIn applies the In predicate on the "date_time" field.
func DateTimeIn(vs ...time.Time) predicate.Call {
	return predicate.Call(sql.FieldIn(FieldDateTime, vs...))
}

// DateTimeNotIn applies the NotIn predicate on the "date_time" field.
func DateTimeNotIn(vs ...time.Time) predicate.Call {
	return predicate.Call(sql.FieldNotIn(FieldDateTime, vs...))
}

// DateTimeGT applies the GT predicate on the "date_time" field.
func DateTimeGT(v time.Time) predicate.Call {
	return predicate.Call(sql.FieldGT(FieldDateTime, v))
}

// DateTimeGTE applies the GTE predicate on the "date_time" field.
func DateTimeGTE(v time.Time) predicate.Call {
	return predicate.Call(sql.FieldGTE(FieldDateTime, v))
}

// DateTimeLT applies the LT predicate on the "date_time" field.
func DateTimeLT(v time.Time) predicate.Call {
	return predicate.Call(sql.FieldLT(FieldDateTime, v))
}

// DateTimeLTE applies the LTE predicate on the "date_time" field.
func DateTimeLTE(v time.Time) predicate.Call {
	return predicate.Call(sql.FieldLTE(FieldDateTime, v))
}

// FrequenciesEQ applies the EQ predicate on the "frequencies" field.
func FrequenciesEQ(v string) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldFrequencies, v))
}

// FrequenciesNEQ applies the NEQ predicate on the "frequencies" field.
func FrequenciesNEQ(v string) predicate.Call {
	return predicate.Call(sql.FieldNEQ(FieldFrequencies, v))
}

// FrequenciesIn applies the In predicate on the "frequencies" field.
func FrequenciesIn(vs ...string) predicate.Call {
	return predicate.Call(sql.FieldIn(FieldFrequencies, vs...))
}

// FrequenciesNotIn applies the NotIn predicate on the "frequencies" field.
func FrequenciesNotIn(vs ...string) predicate.Call {
	return predicate.Call(sql.FieldNotIn(FieldFrequencies, vs...))
}

// FrequenciesGT applies the GT predicate on the "frequencies" field.
func FrequenciesGT(v string) predicate.Call {
	return predicate.Call(sql.FieldGT(FieldFrequencies, v))
}

// FrequenciesGTE applies the GTE predicate on the "frequencies" field.
func FrequenciesGTE(v string) predicate.Call {
	return predicate.Call(sql.FieldGTE(FieldFrequencies, v))
}

// FrequenciesLT applies the LT predicate on the "frequencies" field.
func FrequenciesLT(v string) predicate.Call {
	return predicate.Call(sql.FieldLT(FieldFrequencies, v))
}

// FrequenciesLTE applies the LTE predicate on the "frequencies" field.
func FrequenciesLTE(v string) predicate.Call {
	return predicate.Call(sql.FieldLTE(FieldFrequencies, v))
}

// FrequenciesContains applies the Contains predicate on the "frequencies" field.
func FrequenciesContains(v string) predicate.Call {
	return predicate.Call(sql.FieldContains(FieldFrequencies, v))
}

// FrequenciesHasPrefix applies the HasPrefix predicate on the "frequencies" field.
func FrequenciesHasPrefix(v string) predicate.Call {
	return predicate.Call(sql.FieldHasPrefix(FieldFrequencies, v))
}

// FrequenciesHasSuffix applies the HasSuffix predicate on the "frequencies" field.
func FrequenciesHasSuffix(v string) predicate.Call {
	return predicate.Call(sql.FieldHasSuffix(FieldFrequencies, v))
}

// FrequenciesEqualFold applies the EqualFold predicate on the "frequencies" field.
func FrequenciesEqualFold(v string) predicate.Call {
	return predicate.Call(sql.FieldEqualFold(FieldFrequencies, v))
}

// FrequenciesContainsFold applies the ContainsFold predicate on the "frequencies" field.
func FrequenciesContainsFold(v string) predicate.Call {
	return predicate.Call(sql.FieldContainsFold(FieldFrequencies, v))
}

// FrequencyEQ applies the EQ predicate on the "frequency" field.
func FrequencyEQ(v int) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldFrequency, v))
}

// FrequencyNEQ applies the NEQ predicate on the "frequency" field.
func FrequencyNEQ(v int) predicate.Call {
	return predicate.Call(sql.FieldNEQ(FieldFrequency, v))
}

// FrequencyIn applies the In predicate on the "frequency" field.
func FrequencyIn(vs ...int) predicate.Call {
	return predicate.Call(sql.FieldIn(FieldFrequency, vs...))
}

// FrequencyNotIn applies the NotIn predicate on the "frequency" field.
func FrequencyNotIn(vs ...int) predicate.Call {
	return predicate.Call(sql.FieldNotIn(FieldFrequency, vs...))
}

// FrequencyGT applies the GT predicate on the "frequency" field.
func FrequencyGT(v int) predicate.Call {
	return predicate.Call(sql.FieldGT(FieldFrequency, v))
}

// FrequencyGTE applies the GTE predicate on the "frequency" field.
func FrequencyGTE(v int) predicate.Call {
	return predicate.Call(sql.FieldGTE(FieldFrequency, v))
}

// FrequencyLT applies the LT predicate on the "frequency" field.
func FrequencyLT(v int) predicate.Call {
	return predicate.Call(sql.FieldLT(FieldFrequency, v))
}

// FrequencyLTE applies the LTE predicate on the "frequency" field.
func FrequencyLTE(v int) predicate.Call {
	return predicate.Call(sql.FieldLTE(FieldFrequency, v))
}

// FrequencyIsNil applies the IsNil predicate on the "frequency" field.
func FrequencyIsNil() predicate.Call {
	return predicate.Call(sql.FieldIsNull(FieldFrequency))
}

// FrequencyNotNil applies the NotNil predicate on the "frequency" field.
func FrequencyNotNil() predicate.Call {
	return predicate.Call(sql.FieldNotNull(FieldFrequency))
}

// PatchesEQ applies the EQ predicate on the "patches" field.
func PatchesEQ(v string) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldPatches, v))
}

// PatchesNEQ applies the NEQ predicate on the "patches" field.
func PatchesNEQ(v string) predicate.Call {
	return predicate.Call(sql.FieldNEQ(FieldPatches, v))
}

// PatchesIn applies the In predicate on the "patches" field.
func PatchesIn(vs ...string) predicate.Call {
	return predicate.Call(sql.FieldIn(FieldPatches, vs...))
}

// PatchesNotIn applies the NotIn predicate on the "patches" field.
func PatchesNotIn(vs ...string) predicate.Call {
	return predicate.Call(sql.FieldNotIn(FieldPatches, vs...))
}

// PatchesGT applies the GT predicate on the "patches" field.
func PatchesGT(v string) predicate.Call {
	return predicate.Call(sql.FieldGT(FieldPatches, v))
}

// PatchesGTE applies the GTE predicate on the "patches" field.
func PatchesGTE(v string) predicate.Call {
	return predicate.Call(sql.FieldGTE(FieldPatches, v))
}

// PatchesLT applies the LT predicate on the "patches" field.
func PatchesLT(v string) predicate.Call {
	return predicate.Call(sql.FieldLT(FieldPatches, v))
}

// PatchesLTE applies the LTE predicate on the "patches" field.
func PatchesLTE(v string) predicate.Call {
	return predicate.Call(sql.FieldLTE(FieldPatches, v))
}

// PatchesContains applies the Contains predicate on the "patches" field.
func PatchesContains(v string) predicate.Call {
	return predicate.Call(sql.FieldContains(FieldPatches, v))
}

// PatchesHasPrefix applies the HasPrefix predicate on the "patches" field.
func PatchesHasPrefix(v string) predicate.Call {
	return predicate.Call(sql.FieldHasPrefix(FieldPatches, v))
}

// PatchesHasSuffix applies the HasSuffix predicate on the "patches" field.
func PatchesHasSuffix(v string) predicate.Call {
	return predicate.Call(sql.FieldHasSuffix(FieldPatches, v))
}

// PatchesEqualFold applies the EqualFold predicate on the "patches" field.
func PatchesEqualFold(v string) predicate.Call {
	return predicate.Call(sql.FieldEqualFold(FieldPatches, v))
}

// PatchesContainsFold applies the ContainsFold predicate on the "patches" field.
func PatchesContainsFold(v string) predicate.Call {
	return predicate.Call(sql.FieldContainsFold(FieldPatches, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v int) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v int) predicate.Call {
	return predicate.Call(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...int) predicate.Call {
	return predicate.Call(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...int) predicate.Call {
	return predicate.Call(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v int) predicate.Call {
	return predicate.Call(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v int) predicate.Call {
	return predicate.Call(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v int) predicate.Call {
	return predicate.Call(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v int) predicate.Call {
	return predicate.Call(sql.FieldLTE(FieldSource, v))
}

// SourceIsNil applies the IsNil predicate on the "source" field.
func SourceIsNil() predicate.Call {
	return predicate.Call(sql.FieldIsNull(FieldSource))
}

// SourceNotNil applies the NotNil predicate on the "source" field.
func SourceNotNil() predicate.Call {
	return predicate.Call(sql.FieldNotNull(FieldSource))
}

// SourcesEQ applies the EQ predicate on the "sources" field.
func SourcesEQ(v string) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldSources, v))
}

// SourcesNEQ applies the NEQ predicate on the "sources" field.
func SourcesNEQ(v string) predicate.Call {
	return predicate.Call(sql.FieldNEQ(FieldSources, v))
}

// SourcesIn applies the In predicate on the "sources" field.
func SourcesIn(vs ...string) predicate.Call {
	return predicate.Call(sql.FieldIn(FieldSources, vs...))
}

// SourcesNotIn applies the NotIn predicate on the "sources" field.
func SourcesNotIn(vs ...string) predicate.Call {
	return predicate.Call(sql.FieldNotIn(FieldSources, vs...))
}

// SourcesGT applies the GT predicate on the "sources" field.
func SourcesGT(v string) predicate.Call {
	return predicate.Call(sql.FieldGT(FieldSources, v))
}

// SourcesGTE applies the GTE predicate on the "sources" field.
func SourcesGTE(v string) predicate.Call {
	return predicate.Call(sql.FieldGTE(FieldSources, v))
}

// SourcesLT applies the LT predicate on the "sources" field.
func SourcesLT(v string) predicate.Call {
	return predicate.Call(sql.FieldLT(FieldSources, v))
}

// SourcesLTE applies the LTE predicate on the "sources" field.
func SourcesLTE(v string) predicate.Call {
	return predicate.Call(sql.FieldLTE(FieldSources, v))
}

// SourcesContains applies the Contains predicate on the "sources" field.
func SourcesContains(v string) predicate.Call {
	return predicate.Call(sql.FieldContains(FieldSources, v))
}

// SourcesHasPrefix applies the HasPrefix predicate on the "sources" field.
func SourcesHasPrefix(v string) predicate.Call {
	return predicate.Call(sql.FieldHasPrefix(FieldSources, v))
}

// SourcesHasSuffix applies the HasSuffix predicate on the "sources" field.
func SourcesHasSuffix(v string) predicate.Call {
	return predicate.Call(sql.FieldHasSuffix(FieldSources, v))
}

// SourcesEqualFold applies the EqualFold predicate on the "sources" field.
func SourcesEqualFold(v string) predicate.Call {
	return predicate.Call(sql.FieldEqualFold(FieldSources, v))
}

// SourcesContainsFold applies the ContainsFold predicate on the "sources" field.
func SourcesContainsFold(v string) predicate.Call {
	return predicate.Call(sql.FieldContainsFold(FieldSources, v))
}

// SystemEQ applies the EQ predicate on the "system" field.
func SystemEQ(v int) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldSystem, v))
}

// SystemNEQ applies the NEQ predicate on the "system" field.
func SystemNEQ(v int) predicate.Call {
	return predicate.Call(sql.FieldNEQ(FieldSystem, v))
}

// SystemIn applies the In predicate on the "system" field.
func SystemIn(vs ...int) predicate.Call {
	return predicate.Call(sql.FieldIn(FieldSystem, vs...))
}

// SystemNotIn applies the NotIn predicate on the "system" field.
func SystemNotIn(vs ...int) predicate.Call {
	return predicate.Call(sql.FieldNotIn(FieldSystem, vs...))
}

// SystemGT applies the GT predicate on the "system" field.
func SystemGT(v int) predicate.Call {
	return predicate.Call(sql.FieldGT(FieldSystem, v))
}

// SystemGTE applies the GTE predicate on the "system" field.
func SystemGTE(v int) predicate.Call {
	return predicate.Call(sql.FieldGTE(FieldSystem, v))
}

// SystemLT applies the LT predicate on the "system" field.
func SystemLT(v int) predicate.Call {
	return predicate.Call(sql.FieldLT(FieldSystem, v))
}

// SystemLTE applies the LTE predicate on the "system" field.
func SystemLTE(v int) predicate.Call {
	return predicate.Call(sql.FieldLTE(FieldSystem, v))
}

// TalkgroupEQ applies the EQ predicate on the "talkgroup" field.
func TalkgroupEQ(v int) predicate.Call {
	return predicate.Call(sql.FieldEQ(FieldTalkgroup, v))
}

// TalkgroupNEQ applies the NEQ predicate on the "talkgroup" field.
func TalkgroupNEQ(v int) predicate.Call {
	return predicate.Call(sql.FieldNEQ(FieldTalkgroup, v))
}

// TalkgroupIn applies the In predicate on the "talkgroup" field.
func TalkgroupIn(vs ...int) predicate.Call {
	return predicate.Call(sql.FieldIn(FieldTalkgroup, vs...))
}

// TalkgroupNotIn applies the NotIn predicate on the "talkgroup" field.
func TalkgroupNotIn(vs ...int) predicate.Call {
	return predicate.Call(sql.FieldNotIn(FieldTalkgroup, vs...))
}

// TalkgroupGT applies the GT predicate on the "talkgroup" field.
func TalkgroupGT(v int) predicate.Call {
	return predicate.Call(sql.FieldGT(FieldTalkgroup, v))
}

// TalkgroupGTE applies the GTE predicate on the "talkgroup" field.
func TalkgroupGTE(v int) predicate.Call {
	return predicate.Call(sql.FieldGTE(FieldTalkgroup, v))
}

// TalkgroupLT applies the LT predicate on the "talkgroup" field.
func TalkgroupLT(v int) predicate.Call {
	return predicate.Call(sql.FieldLT(FieldTalkgroup, v))
}

// TalkgroupLTE applies the LTE predicate on the "talkgroup" field.
func TalkgroupLTE(v int) predicate.Call {
	return predicate.Call(sql.FieldLTE(FieldTalkgroup, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Call) predicate.Call {
	return predicate.Call(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Call) predicate.Call {
	return predicate.Call(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Call) predicate.Call {
	return predicate.Call(sql.NotPredicates(p))
}
