// Code generated by ent, DO NOT EDIT.

package unit

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the unit type in the database.
	Label = "unit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "_id"
	// FieldUnitID holds the string denoting the unit_id field in the database.
	FieldUnitID = "id"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldOrder holds the string denoting the order field in the database.
	FieldOrder = "order"
	// FieldSystemID holds the string denoting the system_id field in the database.
	FieldSystemID = "systemid"
	// Table holds the table name of the unit in the database.
	Table = "rdioscannerunits"
)

// Columns holds all SQL columns for unit fields.
var Columns = []string{
	FieldID,
	FieldUnitID,
	FieldLabel,
	FieldOrder,
	FieldSystemID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Unit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUnitID orders the results by the unit_id field.
func ByUnitID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitID, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByOrder orders the results by the order field.
func ByOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrder, opts...).ToFunc()
}

// BySystemID orders the results by the system_id field.
func BySystemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystemID, opts...).ToFunc()
}
