// Code generated by ent, DO NOT EDIT.

package dirwatch

import (
	"entgo.io/ent/dialect/sql"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLTE(FieldID, id))
}

// Delay applies equality check predicate on the "delay" field. It's identical to DelayEQ.
func Delay(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldDelay, v))
}

// DeleteAfter applies equality check predicate on the "delete_after" field. It's identical to DeleteAfterEQ.
func DeleteAfter(v bool) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldDeleteAfter, v))
}

// Directory applies equality check predicate on the "directory" field. It's identical to DirectoryEQ.
func Directory(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldDirectory, v))
}

// Disabled applies equality check predicate on the "disabled" field. It's identical to DisabledEQ.
func Disabled(v bool) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldDisabled, v))
}

// Extension applies equality check predicate on the "extension" field. It's identical to ExtensionEQ.
func Extension(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldExtension, v))
}

// Frequency applies equality check predicate on the "frequency" field. It's identical to FrequencyEQ.
func Frequency(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldFrequency, v))
}

// Mask applies equality check predicate on the "mask" field. It's identical to MaskEQ.
func Mask(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldMask, v))
}

// Order applies equality check predicate on the "order" field. It's identical to OrderEQ.
func Order(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldOrder, v))
}

// SystemID applies equality check predicate on the "system_id" field. It's identical to SystemIDEQ.
func SystemID(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldSystemID, v))
}

// TalkgroupID applies equality check predicate on the "talkgroup_id" field. It's identical to TalkgroupIDEQ.
func TalkgroupID(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldTalkgroupID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldType, v))
}

// UsePolling applies equality check predicate on the "use_polling" field. It's identical to UsePollingEQ.
func UsePolling(v bool) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldUsePolling, v))
}

// DelayEQ applies the EQ predicate on the "delay" field.
func DelayEQ(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldDelay, v))
}

// DelayNEQ applies the NEQ predicate on the "delay" field.
func DelayNEQ(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNEQ(FieldDelay, v))
}

// DelayIn applies the In predicate on the "delay" field.
func DelayIn(vs ...int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIn(FieldDelay, vs...))
}

// DelayNotIn applies the NotIn predicate on the "delay" field.
func DelayNotIn(vs ...int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotIn(FieldDelay, vs...))
}

// DelayGT applies the GT predicate on the "delay" field.
func DelayGT(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGT(FieldDelay, v))
}

// DelayGTE applies the GTE predicate on the "delay" field.
func DelayGTE(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGTE(FieldDelay, v))
}

// DelayLT applies the LT predicate on the "delay" field.
func DelayLT(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLT(FieldDelay, v))
}

// DelayLTE applies the LTE predicate on the "delay" field.
func DelayLTE(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLTE(FieldDelay, v))
}

// DelayIsNil applies the IsNil predicate on the "delay" field.
func DelayIsNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIsNull(FieldDelay))
}

// DelayNotNil applies the NotNil predicate on the "delay" field.
func DelayNotNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotNull(FieldDelay))
}

// DeleteAfterEQ applies the EQ predicate on the "delete_after" field.
func DeleteAfterEQ(v bool) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldDeleteAfter, v))
}

// DeleteAfterNEQ applies the NEQ predicate on the "delete_after" field.
func DeleteAfterNEQ(v bool) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNEQ(FieldDeleteAfter, v))
}

// DeleteAfterIsNil applies the IsNil predicate on the "delete_after" field.
func DeleteAfterIsNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIsNull(FieldDeleteAfter))
}

// DeleteAfterNotNil applies the NotNil predicate on the "delete_after" field.
func DeleteAfterNotNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotNull(FieldDeleteAfter))
}

// DirectoryEQ applies the EQ predicate on the "directory" field.
func DirectoryEQ(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldDirectory, v))
}

// DirectoryNEQ applies the NEQ predicate on the "directory" field.
func DirectoryNEQ(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNEQ(FieldDirectory, v))
}

// DirectoryIn applies the In predicate on the "directory" field.
func DirectoryIn(vs ...string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIn(FieldDirectory, vs...))
}

// DirectoryNotIn applies the NotIn predicate on the "directory" field.
func DirectoryNotIn(vs ...string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotIn(FieldDirectory, vs...))
}

// DirectoryGT applies the GT predicate on the "directory" field.
func DirectoryGT(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGT(FieldDirectory, v))
}

// DirectoryGTE applies the GTE predicate on the "directory" field.
func DirectoryGTE(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGTE(FieldDirectory, v))
}

// DirectoryLT applies the LT predicate on the "directory" field.
func DirectoryLT(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLT(FieldDirectory, v))
}

// DirectoryLTE applies the LTE predicate on the "directory" field.
func DirectoryLTE(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLTE(FieldDirectory, v))
}

// DirectoryContains applies the Contains predicate on the "directory" field.
func DirectoryContains(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldContains(FieldDirectory, v))
}

// DirectoryHasPrefix applies the HasPrefix predicate on the "directory" field.
func DirectoryHasPrefix(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldHasPrefix(FieldDirectory, v))
}

// DirectoryHasSuffix applies the HasSuffix predicate on the "directory" field.
func DirectoryHasSuffix(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldHasSuffix(FieldDirectory, v))
}

// DirectoryEqualFold applies the EqualFold predicate on the "directory" field.
func DirectoryEqualFold(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEqualFold(FieldDirectory, v))
}

// DirectoryContainsFold applies the ContainsFold predicate on the "directory" field.
func DirectoryContainsFold(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldContainsFold(FieldDirectory, v))
}

// DisabledEQ applies the EQ predicate on the "disabled" field.
func DisabledEQ(v bool) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldDisabled, v))
}

// DisabledNEQ applies the NEQ predicate on the "disabled" field.
func DisabledNEQ(v bool) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNEQ(FieldDisabled, v))
}

// DisabledIsNil applies the IsNil predicate on the "disabled" field.
func DisabledIsNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIsNull(FieldDisabled))
}

// DisabledNotNil applies the NotNil predicate on the "disabled" field.
func DisabledNotNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotNull(FieldDisabled))
}

// ExtensionEQ applies the EQ predicate on the "extension" field.
func ExtensionEQ(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldExtension, v))
}

// ExtensionNEQ applies the NEQ predicate on the "extension" field.
func ExtensionNEQ(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNEQ(FieldExtension, v))
}

// ExtensionIn applies the In predicate on the "extension" field.
func ExtensionIn(vs ...string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIn(FieldExtension, vs...))
}

// ExtensionNotIn applies the NotIn predicate on the "extension" field.
func ExtensionNotIn(vs ...string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotIn(FieldExtension, vs...))
}

// ExtensionGT applies the GT predicate on the "extension" field.
func ExtensionGT(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGT(FieldExtension, v))
}

// ExtensionGTE applies the GTE predicate on the "extension" field.
func ExtensionGTE(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGTE(FieldExtension, v))
}

// ExtensionLT applies the LT predicate on the "extension" field.
func ExtensionLT(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLT(FieldExtension, v))
}

// ExtensionLTE applies the LTE predicate on the "extension" field.
func ExtensionLTE(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLTE(FieldExtension, v))
}

// ExtensionContains applies the Contains predicate on the "extension" field.
func ExtensionContains(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldContains(FieldExtension, v))
}

// ExtensionHasPrefix applies the HasPrefix predicate on the "extension" field.
func ExtensionHasPrefix(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldHasPrefix(FieldExtension, v))
}

// ExtensionHasSuffix applies the HasSuffix predicate on the "extension" field.
func ExtensionHasSuffix(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldHasSuffix(FieldExtension, v))
}

// ExtensionIsNil applies the IsNil predicate on the "extension" field.
func ExtensionIsNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIsNull(FieldExtension))
}

// ExtensionNotNil applies the NotNil predicate on the "extension" field.
func ExtensionNotNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotNull(FieldExtension))
}

// ExtensionEqualFold applies the EqualFold predicate on the "extension" field.
func ExtensionEqualFold(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEqualFold(FieldExtension, v))
}

// ExtensionContainsFold applies the ContainsFold predicate on the "extension" field.
func ExtensionContainsFold(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldContainsFold(FieldExtension, v))
}

// FrequencyEQ applies the EQ predicate on the "frequency" field.
func FrequencyEQ(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldFrequency, v))
}

// FrequencyNEQ applies the NEQ predicate on the "frequency" field.
func FrequencyNEQ(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNEQ(FieldFrequency, v))
}

// FrequencyIn applies the In predicate on the "frequency" field.
func FrequencyIn(vs ...int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIn(FieldFrequency, vs...))
}

// FrequencyNotIn applies the NotIn predicate on the "frequency" field.
func FrequencyNotIn(vs ...int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotIn(FieldFrequency, vs...))
}

// FrequencyGT applies the GT predicate on the "frequency" field.
func FrequencyGT(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGT(FieldFrequency, v))
}

// FrequencyGTE applies the GTE predicate on the "frequency" field.
func FrequencyGTE(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGTE(FieldFrequency, v))
}

// FrequencyLT applies the LT predicate on the "frequency" field.
func FrequencyLT(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLT(FieldFrequency, v))
}

// FrequencyLTE applies the LTE predicate on the "frequency" field.
func FrequencyLTE(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLTE(FieldFrequency, v))
}

// FrequencyIsNil applies the IsNil predicate on the "frequency" field.
func FrequencyIsNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIsNull(FieldFrequency))
}

// FrequencyNotNil applies the NotNil predicate on the "frequency" field.
func FrequencyNotNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotNull(FieldFrequency))
}

// MaskEQ applies the EQ predicate on the "mask" field.
func MaskEQ(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldMask, v))
}

// MaskNEQ applies the NEQ predicate on the "mask" field.
func MaskNEQ(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNEQ(FieldMask, v))
}

// MaskIn applies the In predicate on the "mask" field.
func MaskIn(vs ...string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIn(FieldMask, vs...))
}

// MaskNotIn applies the NotIn predicate on the "mask" field.
func MaskNotIn(vs ...string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotIn(FieldMask, vs...))
}

// MaskGT applies the GT predicate on the "mask" field.
func MaskGT(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGT(FieldMask, v))
}

// MaskGTE applies the GTE predicate on the "mask" field.
func MaskGTE(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGTE(FieldMask, v))
}

// MaskLT applies the LT predicate on the "mask" field.
func MaskLT(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLT(FieldMask, v))
}

// MaskLTE applies the LTE predicate on the "mask" field.
func MaskLTE(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLTE(FieldMask, v))
}

// MaskContains applies the Contains predicate on the "mask" field.
func MaskContains(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldContains(FieldMask, v))
}

// MaskHasPrefix applies the HasPrefix predicate on the "mask" field.
func MaskHasPrefix(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldHasPrefix(FieldMask, v))
}

// MaskHasSuffix applies the HasSuffix predicate on the "mask" field.
func MaskHasSuffix(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldHasSuffix(FieldMask, v))
}

// MaskIsNil applies the IsNil predicate on the "mask" field.
func MaskIsNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIsNull(FieldMask))
}

// MaskNotNil applies the NotNil predicate on the "mask" field.
func MaskNotNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotNull(FieldMask))
}

// MaskEqualFold applies the EqualFold predicate on the "mask" field.
func MaskEqualFold(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEqualFold(FieldMask, v))
}

// MaskContainsFold applies the ContainsFold predicate on the "mask" field.
func MaskContainsFold(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldContainsFold(FieldMask, v))
}

// OrderEQ applies the EQ predicate on the "order" field.
func OrderEQ(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldOrder, v))
}

// OrderNEQ applies the NEQ predicate on the "order" field.
func OrderNEQ(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNEQ(FieldOrder, v))
}

// OrderIn applies the In predicate on the "order" field.
func OrderIn(vs ...int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIn(FieldOrder, vs...))
}

// OrderNotIn applies the NotIn predicate on the "order" field.
func OrderNotIn(vs ...int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotIn(FieldOrder, vs...))
}

// OrderGT applies the GT predicate on the "order" field.
func OrderGT(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGT(FieldOrder, v))
}

// OrderGTE applies the GTE predicate on the "order" field.
func OrderGTE(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGTE(FieldOrder, v))
}

// OrderLT applies the LT predicate on the "order" field.
func OrderLT(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLT(FieldOrder, v))
}

// OrderLTE applies the LTE predicate on the "order" field.
func OrderLTE(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLTE(FieldOrder, v))
}

// OrderIsNil applies the IsNil predicate on the "order" field.
func OrderIsNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIsNull(FieldOrder))
}

// OrderNotNil applies the NotNil predicate on the "order" field.
func OrderNotNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotNull(FieldOrder))
}

// SystemIDEQ applies the EQ predicate on the "system_id" field.
func SystemIDEQ(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldSystemID, v))
}

// SystemIDNEQ applies the NEQ predicate on the "system_id" field.
func SystemIDNEQ(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNEQ(FieldSystemID, v))
}

// SystemIDIn applies the In predicate on the "system_id" field.
func SystemIDIn(vs ...int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIn(FieldSystemID, vs...))
}

// SystemIDNotIn applies the NotIn predicate on the "system_id" field.
func SystemIDNotIn(vs ...int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotIn(FieldSystemID, vs...))
}

// SystemIDGT applies the GT predicate on the "system_id" field.
func SystemIDGT(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGT(FieldSystemID, v))
}

// SystemIDGTE applies the GTE predicate on the "system_id" field.
func SystemIDGTE(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGTE(FieldSystemID, v))
}

// SystemIDLT applies the LT predicate on the "system_id" field.
func SystemIDLT(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLT(FieldSystemID, v))
}

// SystemIDLTE applies the LTE predicate on the "system_id" field.
func SystemIDLTE(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLTE(FieldSystemID, v))
}

// SystemIDIsNil applies the IsNil predicate on the "system_id" field.
func SystemIDIsNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIsNull(FieldSystemID))
}

// SystemIDNotNil applies the NotNil predicate on the "system_id" field.
func SystemIDNotNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotNull(FieldSystemID))
}

// TalkgroupIDEQ applies the EQ predicate on the "talkgroup_id" field.
func TalkgroupIDEQ(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldTalkgroupID, v))
}

// TalkgroupIDNEQ applies the NEQ predicate on the "talkgroup_id" field.
func TalkgroupIDNEQ(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNEQ(FieldTalkgroupID, v))
}

// TalkgroupIDIn applies the In predicate on the "talkgroup_id" field.
func TalkgroupIDIn(vs ...int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIn(FieldTalkgroupID, vs...))
}

// TalkgroupIDNotIn applies the NotIn predicate on the "talkgroup_id" field.
func TalkgroupIDNotIn(vs ...int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotIn(FieldTalkgroupID, vs...))
}

// TalkgroupIDGT applies the GT predicate on the "talkgroup_id" field.
func TalkgroupIDGT(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGT(FieldTalkgroupID, v))
}

// TalkgroupIDGTE applies the GTE predicate on the "talkgroup_id" field.
func TalkgroupIDGTE(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGTE(FieldTalkgroupID, v))
}

// TalkgroupIDLT applies the LT predicate on the "talkgroup_id" field.
func TalkgroupIDLT(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLT(FieldTalkgroupID, v))
}

// TalkgroupIDLTE applies the LTE predicate on the "talkgroup_id" field.
func TalkgroupIDLTE(v int) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLTE(FieldTalkgroupID, v))
}

// TalkgroupIDIsNil applies the IsNil predicate on the "talkgroup_id" field.
func TalkgroupIDIsNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIsNull(FieldTalkgroupID))
}

// TalkgroupIDNotNil applies the NotNil predicate on the "talkgroup_id" field.
func TalkgroupIDNotNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotNull(FieldTalkgroupID))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldHasSuffix(FieldType, v))
}

// TypeIsNil applies the IsNil predicate on the "type" field.
func TypeIsNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIsNull(FieldType))
}

// TypeNotNil applies the NotNil predicate on the "type" field.
func TypeNotNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotNull(FieldType))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldContainsFold(FieldType, v))
}

// UsePollingEQ applies the EQ predicate on the "use_polling" field.
func UsePollingEQ(v bool) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldEQ(FieldUsePolling, v))
}

// UsePollingNEQ applies the NEQ predicate on the "use_polling" field.
func UsePollingNEQ(v bool) predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNEQ(FieldUsePolling, v))
}

// UsePollingIsNil applies the IsNil predicate on the "use_polling" field.
func UsePollingIsNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldIsNull(FieldUsePolling))
}

// UsePollingNotNil applies the NotNil predicate on the "use_polling" field.
func UsePollingNotNil() predicate.Dirwatch {
	return predicate.Dirwatch(sql.FieldNotNull(FieldUsePolling))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Dirwatch) predicate.Dirwatch {
	return predicate.Dirwatch(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Dirwatch) predicate.Dirwatch {
	return predicate.Dirwatch(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Dirwatch) predicate.Dirwatch {
	return predicate.Dirwatch(sql.NotPredicates(p))
}
