// Code generated by ent, DO NOT EDIT.

package access

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the access type in the database.
	Label = "access"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "_id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldExpiration holds the string denoting the expiration field in the database.
	FieldExpiration = "expiration"
	// FieldIdent holds the string denoting the ident field in the database.
	FieldIdent = "ident"
	// FieldLimit holds the string denoting the limit field in the database.
	FieldLimit = "limit"
	// FieldOrder holds the string denoting the order field in the database.
	FieldOrder = "order"
	// FieldSystems holds the string denoting the systems field in the database.
	FieldSystems = "systems"
	// Table holds the table name of the access in the database.
	Table = "rdioscanneraccesses"
)

// Columns holds all SQL columns for access fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldExpiration,
	FieldIdent,
	FieldLimit,
	FieldOrder,
	FieldSystems,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Access queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByExpiration orders the results by the expiration field.
func ByExpiration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiration, opts...).ToFunc()
}

// ByIdent orders the results by the ident field.
func ByIdent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdent, opts...).ToFunc()
}

// ByLimit orders the results by the limit field.
func ByLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLimit, opts...).ToFunc()
}

// ByOrder orders the results by the order field.
func ByOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrder, opts...).ToFunc()
}

// BySystems orders the results by the systems field.
func BySystems(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystems, opts...).ToFunc()
}
