// Code generated by ent, DO NOT EDIT.

package access

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Access {
	return predicate.Access(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Access {
	return predicate.Access(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Access {
	return predicate.Access(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Access {
	return predicate.Access(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Access {
	return predicate.Access(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Access {
	return predicate.Access(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Access {
	return predicate.Access(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Access {
	return predicate.Access(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Access {
	return predicate.Access(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Access {
	return predicate.Access(sql.FieldEQ(FieldCode, v))
}

// Expiration applies equality check predicate on the "expiration" field. It's identical to ExpirationEQ.
func Expiration(v time.Time) predicate.Access {
	return predicate.Access(sql.FieldEQ(FieldExpiration, v))
}

// Ident applies equality check predicate on the "ident" field. It's identical to IdentEQ.
func Ident(v string) predicate.Access {
	return predicate.Access(sql.FieldEQ(FieldIdent, v))
}

// Limit applies equality check predicate on the "limit" field. It's identical to LimitEQ.
func Limit(v int) predicate.Access {
	return predicate.Access(sql.FieldEQ(FieldLimit, v))
}

// Order applies equality check predicate on the "order" field. It's identical to OrderEQ.
func Order(v int) predicate.Access {
	return predicate.Access(sql.FieldEQ(FieldOrder, v))
}

// Systems applies equality check predicate on the "systems" field. It's identical to SystemsEQ.
func Systems(v string) predicate.Access {
	return predicate.Access(sql.FieldEQ(FieldSystems, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Access {
	return predicate.Access(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Access {
	return predicate.Access(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Access {
	return predicate.Access(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Access {
	return predicate.Access(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Access {
	return predicate.Access(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Access {
	return predicate.Access(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Access {
	return predicate.Access(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Access {
	return predicate.Access(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Access {
	return predicate.Access(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Access {
	return predicate.Access(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Access {
	return predicate.Access(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Access {
	return predicate.Access(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Access {
	return predicate.Access(sql.FieldContainsFold(FieldCode, v))
}

// ExpirationEQ applies the EQ predicate on the "expiration" field.
func ExpirationEQ(v time.Time) predicate.Access {
	return predicate.Access(sql.FieldEQ(FieldExpiration, v))
}

// ExpirationNEQ applies the NEQ predicate on the "expiration" field.
func ExpirationNEQ(v time.Time) predicate.Access {
	return predicate.Access(sql.FieldNEQ(FieldExpiration, v))
}

// ExpirationIn applies the In predicate on the "expiration" field.
func ExpirationIn(vs ...time.Time) predicate.Access {
	return predicate.Access(sql.FieldIn(FieldExpiration, vs...))
}

// ExpirationNotIn applies the NotIn predicate on the "expiration" field.
func ExpirationNotIn(vs ...time.Time) predicate.Access {
	return predicate.Access(sql.FieldNotIn(FieldExpiration, vs...))
}

// ExpirationGT applies the GT predicate on the "expiration" field.
func ExpirationGT(v time.Time) predicate.Access {
	return predicate.Access(sql.FieldGT(FieldExpiration, v))
}

// ExpirationGTE applies the GTE predicate on the "expiration" field.
func ExpirationGTE(v time.Time) predicate.Access {
	return predicate.Access(sql.FieldGTE(FieldExpiration, v))
}

// ExpirationLT applies the LT predicate on the "expiration" field.
func ExpirationLT(v time.Time) predicate.Access {
	return predicate.Access(sql.FieldLT(FieldExpiration, v))
}

// ExpirationLTE applies the LTE predicate on the "expiration" field.
func ExpirationLTE(v time.Time) predicate.Access {
	return predicate.Access(sql.FieldLTE(FieldExpiration, v))
}

// ExpirationIsNil applies the IsNil predicate on the "expiration" field.
func ExpirationIsNil() predicate.Access {
	return predicate.Access(sql.FieldIsNull(FieldExpiration))
}

// ExpirationNotNil applies the NotNil predicate on the "expiration" field.
func ExpirationNotNil() predicate.Access {
	return predicate.Access(sql.FieldNotNull(FieldExpiration))
}

// IdentEQ applies the EQ predicate on the "ident" field.
func IdentEQ(v string) predicate.Access {
	return predicate.Access(sql.FieldEQ(FieldIdent, v))
}

// IdentNEQ applies the NEQ predicate on the "ident" field.
func IdentNEQ(v string) predicate.Access {
	return predicate.Access(sql.FieldNEQ(FieldIdent, v))
}

// IdentIn applies the In predicate on the "ident" field.
func IdentIn(vs ...string) predicate.Access {
	return predicate.Access(sql.FieldIn(FieldIdent, vs...))
}

// IdentNotIn applies the NotIn predicate on the "ident" field.
func IdentNotIn(vs ...string) predicate.Access {
	return predicate.Access(sql.FieldNotIn(FieldIdent, vs...))
}

// IdentGT applies the GT predicate on the "ident" field.
func IdentGT(v string) predicate.Access {
	return predicate.Access(sql.FieldGT(FieldIdent, v))
}

// IdentGTE applies the GTE predicate on the "ident" field.
func IdentGTE(v string) predicate.Access {
	return predicate.Access(sql.FieldGTE(FieldIdent, v))
}

// IdentLT applies the LT predicate on the "ident" field.
func IdentLT(v string) predicate.Access {
	return predicate.Access(sql.FieldLT(FieldIdent, v))
}

// IdentLTE applies the LTE predicate on the "ident" field.
func IdentLTE(v string) predicate.Access {
	return predicate.Access(sql.FieldLTE(FieldIdent, v))
}

// IdentContains applies the Contains predicate on the "ident" field.
func IdentContains(v string) predicate.Access {
	return predicate.Access(sql.FieldContains(FieldIdent, v))
}

// IdentHasPrefix applies the HasPrefix predicate on the "ident" field.
func IdentHasPrefix(v string) predicate.Access {
	return predicate.Access(sql.FieldHasPrefix(FieldIdent, v))
}

// IdentHasSuffix applies the HasSuffix predicate on the "ident" field.
func IdentHasSuffix(v string) predicate.Access {
	return predicate.Access(sql.FieldHasSuffix(FieldIdent, v))
}

// IdentIsNil applies the IsNil predicate on the "ident" field.
func IdentIsNil() predicate.Access {
	return predicate.Access(sql.FieldIsNull(FieldIdent))
}

// IdentNotNil applies the NotNil predicate on the "ident" field.
func IdentNotNil() predicate.Access {
	return predicate.Access(sql.FieldNotNull(FieldIdent))
}

// IdentEqualFold applies the EqualFold predicate on the "ident" field.
func IdentEqualFold(v string) predicate.Access {
	return predicate.Access(sql.FieldEqualFold(FieldIdent, v))
}

// IdentContainsFold applies the ContainsFold predicate on the "ident" field.
func IdentContainsFold(v string) predicate.Access {
	return predicate.Access(sql.FieldContainsFold(FieldIdent, v))
}

// LimitEQ applies the EQ predicate on the "limit" field.
func LimitEQ(v int) predicate.Access {
	return predicate.Access(sql.FieldEQ(FieldLimit, v))
}

// LimitNEQ applies the NEQ predicate on the "limit" field.
func LimitNEQ(v int) predicate.Access {
	return predicate.Access(sql.FieldNEQ(FieldLimit, v))
}

// LimitIn applies the In predicate on the "limit" field.
func LimitIn(vs ...int) predicate.Access {
	return predicate.Access(sql.FieldIn(FieldLimit, vs...))
}

// LimitNotIn applies the NotIn predicate on the "limit" field.
func LimitNotIn(vs ...int) predicate.Access {
	return predicate.Access(sql.FieldNotIn(FieldLimit, vs...))
}

// LimitGT applies the GT predicate on the "limit" field.
func LimitGT(v int) predicate.Access {
	return predicate.Access(sql.FieldGT(FieldLimit, v))
}

// LimitGTE applies the GTE predicate on the "limit" field.
func LimitGTE(v int) predicate.Access {
	return predicate.Access(sql.FieldGTE(FieldLimit, v))
}

// LimitLT applies the LT predicate on the "limit" field.
func LimitLT(v int) predicate.Access {
	return predicate.Access(sql.FieldLT(FieldLimit, v))
}

// LimitLTE applies the LTE predicate on the "limit" field.
func LimitLTE(v int) predicate.Access {
	return predicate.Access(sql.FieldLTE(FieldLimit, v))
}

// LimitIsNil applies the IsNil predicate on the "limit" field.
func LimitIsNil() predicate.Access {
	return predicate.Access(sql.FieldIsNull(FieldLimit))
}

// LimitNotNil applies the NotNil predicate on the "limit" field.
func LimitNotNil() predicate.Access {
	return predicate.Access(sql.FieldNotNull(FieldLimit))
}

// OrderEQ applies the EQ predicate on the "order" field.
func OrderEQ(v int) predicate.Access {
	return predicate.Access(sql.FieldEQ(FieldOrder, v))
}

// OrderNEQ applies the NEQ predicate on the "order" field.
func OrderNEQ(v int) predicate.Access {
	return predicate.Access(sql.FieldNEQ(FieldOrder, v))
}

// OrderIn applies the In predicate on the "order" field.
func OrderIn(vs ...int) predicate.Access {
	return predicate.Access(sql.FieldIn(FieldOrder, vs...))
}

// OrderNotIn applies the NotIn predicate on the "order" field.
func OrderNotIn(vs ...int) predicate.Access {
	return predicate.Access(sql.FieldNotIn(FieldOrder, vs...))
}

// OrderGT applies the GT predicate on the "order" field.
func OrderGT(v int) predicate.Access {
	return predicate.Access(sql.FieldGT(FieldOrder, v))
}

// OrderGTE applies the GTE predicate on the "order" field.
func OrderGTE(v int) predicate.Access {
	return predicate.Access(sql.FieldGTE(FieldOrder, v))
}

// OrderLT applies the LT predicate on the "order" field.
func OrderLT(v int) predicate.Access {
	return predicate.Access(sql.FieldLT(FieldOrder, v))
}

// OrderLTE applies the LTE predicate on the "order" field.
func OrderLTE(v int) predicate.Access {
	return predicate.Access(sql.FieldLTE(FieldOrder, v))
}

// OrderIsNil applies the IsNil predicate on the "order" field.
func OrderIsNil() predicate.Access {
	return predicate.Access(sql.FieldIsNull(FieldOrder))
}

// OrderNotNil applies the NotNil predicate on the "order" field.
func OrderNotNil() predicate.Access {
	return predicate.Access(sql.FieldNotNull(FieldOrder))
}

// SystemsEQ applies the EQ predicate on the "systems" field.
func SystemsEQ(v string) predicate.Access {
	return predicate.Access(sql.FieldEQ(FieldSystems, v))
}

// SystemsNEQ applies the NEQ predicate on the "systems" field.
func SystemsNEQ(v string) predicate.Access {
	return predicate.Access(sql.FieldNEQ(FieldSystems, v))
}

// SystemsIn applies the In predicate on the "systems" field.
func SystemsIn(vs ...string) predicate.Access {
	return predicate.Access(sql.FieldIn(FieldSystems, vs...))
}

// SystemsNotIn applies the NotIn predicate on the "systems" field.
func SystemsNotIn(vs ...string) predicate.Access {
	return predicate.Access(sql.FieldNotIn(FieldSystems, vs...))
}

// SystemsGT applies the GT predicate on the "systems" field.
func SystemsGT(v string) predicate.Access {
	return predicate.Access(sql.FieldGT(FieldSystems, v))
}

// SystemsGTE applies the GTE predicate on the "systems" field.
func SystemsGTE(v string) predicate.Access {
	return predicate.Access(sql.FieldGTE(FieldSystems, v))
}

// SystemsLT applies the LT predicate on the "systems" field.
func SystemsLT(v string) predicate.Access {
	return predicate.Access(sql.FieldLT(FieldSystems, v))
}

// SystemsLTE applies the LTE predicate on the "systems" field.
func SystemsLTE(v string) predicate.Access {
	return predicate.Access(sql.FieldLTE(FieldSystems, v))
}

// SystemsContains applies the Contains predicate on the "systems" field.
func SystemsContains(v string) predicate.Access {
	return predicate.Access(sql.FieldContains(FieldSystems, v))
}

// SystemsHasPrefix applies the HasPrefix predicate on the "systems" field.
func SystemsHasPrefix(v string) predicate.Access {
	return predicate.Access(sql.FieldHasPrefix(FieldSystems, v))
}

// SystemsHasSuffix applies the HasSuffix predicate on the "systems" field.
func SystemsHasSuffix(v string) predicate.Access {
	return predicate.Access(sql.FieldHasSuffix(FieldSystems, v))
}

// SystemsEqualFold applies the EqualFold predicate on the "systems" field.
func SystemsEqualFold(v string) predicate.Access {
	return predicate.Access(sql.FieldEqualFold(FieldSystems, v))
}

// SystemsContainsFold applies the ContainsFold predicate on the "systems" field.
func SystemsContainsFold(v string) predicate.Access {
	return predicate.Access(sql.FieldContainsFold(FieldSystems, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Access) predicate.Access {
	return predicate.Access(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Access) predicate.Access {
	return predicate.Access(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Access) predicate.Access {
	return predicate.Access(sql.NotPredicates(p))
}
