// Code generated by ent, DO NOT EDIT.

package downstream

import (
	"entgo.io/ent/dialect/sql"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Downstream {
	return predicate.Downstream(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Downstream {
	return predicate.Downstream(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Downstream {
	return predicate.Downstream(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Downstream {
	return predicate.Downstream(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Downstream {
	return predicate.Downstream(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Downstream {
	return predicate.Downstream(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Downstream {
	return predicate.Downstream(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Downstream {
	return predicate.Downstream(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Downstream {
	return predicate.Downstream(sql.FieldLTE(FieldID, id))
}

// APIKey applies equality check predicate on the "api_key" field. It's identical to APIKeyEQ.
func APIKey(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldEQ(FieldAPIKey, v))
}

// Disabled applies equality check predicate on the "disabled" field. It's identical to DisabledEQ.
func Disabled(v bool) predicate.Downstream {
	return predicate.Downstream(sql.FieldEQ(FieldDisabled, v))
}

// Order applies equality check predicate on the "order" field. It's identical to OrderEQ.
func Order(v int) predicate.Downstream {
	return predicate.Downstream(sql.FieldEQ(FieldOrder, v))
}

// Systems applies equality check predicate on the "systems" field. It's identical to SystemsEQ.
func Systems(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldEQ(FieldSystems, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldEQ(FieldURL, v))
}

// APIKeyEQ applies the EQ predicate on the "api_key" field.
func APIKeyEQ(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "api_key" field.
func APIKeyNEQ(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "api_key" field.
func APIKeyIn(vs ...string) predicate.Downstream {
	return predicate.Downstream(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "api_key" field.
func APIKeyNotIn(vs ...string) predicate.Downstream {
	return predicate.Downstream(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "api_key" field.
func APIKeyGT(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "api_key" field.
func APIKeyGTE(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "api_key" field.
func APIKeyLT(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "api_key" field.
func APIKeyLTE(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyContains applies the Contains predicate on the "api_key" field.
func APIKeyContains(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldContains(FieldAPIKey, v))
}

// APIKeyHasPrefix applies the HasPrefix predicate on the "api_key" field.
func APIKeyHasPrefix(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldHasPrefix(FieldAPIKey, v))
}

// APIKeyHasSuffix applies the HasSuffix predicate on the "api_key" field.
func APIKeyHasSuffix(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldHasSuffix(FieldAPIKey, v))
}

// APIKeyEqualFold applies the EqualFold predicate on the "api_key" field.
func APIKeyEqualFold(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldEqualFold(FieldAPIKey, v))
}

// APIKeyContainsFold applies the ContainsFold predicate on the "api_key" field.
func APIKeyContainsFold(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldContainsFold(FieldAPIKey, v))
}

// DisabledEQ applies the EQ predicate on the "disabled" field.
func DisabledEQ(v bool) predicate.Downstream {
	return predicate.Downstream(sql.FieldEQ(FieldDisabled, v))
}

// DisabledNEQ applies the NEQ predicate on the "disabled" field.
func DisabledNEQ(v bool) predicate.Downstream {
	return predicate.Downstream(sql.FieldNEQ(FieldDisabled, v))
}

// DisabledIsNil applies the IsNil predicate on the "disabled" field.
func DisabledIsNil() predicate.Downstream {
	return predicate.Downstream(sql.FieldIsNull(FieldDisabled))
}

// DisabledNotNil applies the NotNil predicate on the "disabled" field.
func DisabledNotNil() predicate.Downstream {
	return predicate.Downstream(sql.FieldNotNull(FieldDisabled))
}

// OrderEQ applies the EQ predicate on the "order" field.
func OrderEQ(v int) predicate.Downstream {
	return predicate.Downstream(sql.FieldEQ(FieldOrder, v))
}

// OrderNEQ applies the NEQ predicate on the "order" field.
func OrderNEQ(v int) predicate.Downstream {
	return predicate.Downstream(sql.FieldNEQ(FieldOrder, v))
}

// OrderIn applies the In predicate on the "order" field.
func OrderIn(vs ...int) predicate.Downstream {
	return predicate.Downstream(sql.FieldIn(FieldOrder, vs...))
}

// OrderNotIn applies the NotIn predicate on the "order" field.
func OrderNotIn(vs ...int) predicate.Downstream {
	return predicate.Downstream(sql.FieldNotIn(FieldOrder, vs...))
}

// OrderGT applies the GT predicate on the "order" field.
func OrderGT(v int) predicate.Downstream {
	return predicate.Downstream(sql.FieldGT(FieldOrder, v))
}

// OrderGTE applies the GTE predicate on the "order" field.
func OrderGTE(v int) predicate.Downstream {
	return predicate.Downstream(sql.FieldGTE(FieldOrder, v))
}

// OrderLT applies the LT predicate on the "order" field.
func OrderLT(v int) predicate.Downstream {
	return predicate.Downstream(sql.FieldLT(FieldOrder, v))
}

// OrderLTE applies the LTE predicate on the "order" field.
func OrderLTE(v int) predicate.Downstream {
	return predicate.Downstream(sql.FieldLTE(FieldOrder, v))
}

// OrderIsNil applies the IsNil predicate on the "order" field.
func OrderIsNil() predicate.Downstream {
	return predicate.Downstream(sql.FieldIsNull(FieldOrder))
}

// OrderNotNil applies the NotNil predicate on the "order" field.
func OrderNotNil() predicate.Downstream {
	return predicate.Downstream(sql.FieldNotNull(FieldOrder))
}

// SystemsEQ applies the EQ predicate on the "systems" field.
func SystemsEQ(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldEQ(FieldSystems, v))
}

// SystemsNEQ applies the NEQ predicate on the "systems" field.
func SystemsNEQ(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldNEQ(FieldSystems, v))
}

// SystemsIn applies the In predicate on the "systems" field.
func SystemsIn(vs ...string) predicate.Downstream {
	return predicate.Downstream(sql.FieldIn(FieldSystems, vs...))
}

// SystemsNotIn applies the NotIn predicate on the "systems" field.
func SystemsNotIn(vs ...string) predicate.Downstream {
	return predicate.Downstream(sql.FieldNotIn(FieldSystems, vs...))
}

// SystemsGT applies the GT predicate on the "systems" field.
func SystemsGT(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldGT(FieldSystems, v))
}

// SystemsGTE applies the GTE predicate on the "systems" field.
func SystemsGTE(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldGTE(FieldSystems, v))
}

// SystemsLT applies the LT predicate on the "systems" field.
func SystemsLT(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldLT(FieldSystems, v))
}

// SystemsLTE applies the LTE predicate on the "systems" field.
func SystemsLTE(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldLTE(FieldSystems, v))
}

// SystemsContains applies the Contains predicate on the "systems" field.
func SystemsContains(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldContains(FieldSystems, v))
}

// SystemsHasPrefix applies the HasPrefix predicate on the "systems" field.
func SystemsHasPrefix(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldHasPrefix(FieldSystems, v))
}

// SystemsHasSuffix applies the HasSuffix predicate on the "systems" field.
func SystemsHasSuffix(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldHasSuffix(FieldSystems, v))
}

// SystemsEqualFold applies the EqualFold predicate on the "systems" field.
func SystemsEqualFold(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldEqualFold(FieldSystems, v))
}

// SystemsContainsFold applies the ContainsFold predicate on the "systems" field.
func SystemsContainsFold(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldContainsFold(FieldSystems, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Downstream {
	return predicate.Downstream(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Downstream {
	return predicate.Downstream(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Downstream {
	return predicate.Downstream(sql.FieldContainsFold(FieldURL, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Downstream) predicate.Downstream {
	return predicate.Downstream(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Downstream) predicate.Downstream {
	return predicate.Downstream(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Downstream) predicate.Downstream {
	return predicate.Downstream(sql.NotPredicates(p))
}
