// Code generated by ent, DO NOT EDIT.

package talkgroup

import (
	"entgo.io/ent/dialect/sql"
	"github.com/USA-RedDragon/rdio-scanner/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLTE(FieldID, id))
}

// Frequency applies equality check predicate on the "frequency" field. It's identical to FrequencyEQ.
func Frequency(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldFrequency, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldGroupID, v))
}

// TalkgroupID applies equality check predicate on the "talkgroup_id" field. It's identical to TalkgroupIDEQ.
func TalkgroupID(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldTalkgroupID, v))
}

// Led applies equality check predicate on the "led" field. It's identical to LedEQ.
func Led(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldLed, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldName, v))
}

// Order applies equality check predicate on the "order" field. It's identical to OrderEQ.
func Order(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldOrder, v))
}

// SystemID applies equality check predicate on the "system_id" field. It's identical to SystemIDEQ.
func SystemID(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldSystemID, v))
}

// TagID applies equality check predicate on the "tag_id" field. It's identical to TagIDEQ.
func TagID(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldTagID, v))
}

// FrequencyEQ applies the EQ predicate on the "frequency" field.
func FrequencyEQ(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldFrequency, v))
}

// FrequencyNEQ applies the NEQ predicate on the "frequency" field.
func FrequencyNEQ(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNEQ(FieldFrequency, v))
}

// FrequencyIn applies the In predicate on the "frequency" field.
func FrequencyIn(vs ...int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldIn(FieldFrequency, vs...))
}

// FrequencyNotIn applies the NotIn predicate on the "frequency" field.
func FrequencyNotIn(vs ...int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNotIn(FieldFrequency, vs...))
}

// FrequencyGT applies the GT predicate on the "frequency" field.
func FrequencyGT(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGT(FieldFrequency, v))
}

// FrequencyGTE applies the GTE predicate on the "frequency" field.
func FrequencyGTE(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGTE(FieldFrequency, v))
}

// FrequencyLT applies the LT predicate on the "frequency" field.
func FrequencyLT(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLT(FieldFrequency, v))
}

// FrequencyLTE applies the LTE predicate on the "frequency" field.
func FrequencyLTE(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLTE(FieldFrequency, v))
}

// FrequencyIsNil applies the IsNil predicate on the "frequency" field.
func FrequencyIsNil() predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldIsNull(FieldFrequency))
}

// FrequencyNotNil applies the NotNil predicate on the "frequency" field.
func FrequencyNotNil() predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNotNull(FieldFrequency))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLTE(FieldGroupID, v))
}

// TalkgroupIDEQ applies the EQ predicate on the "talkgroup_id" field.
func TalkgroupIDEQ(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldTalkgroupID, v))
}

// TalkgroupIDNEQ applies the NEQ predicate on the "talkgroup_id" field.
func TalkgroupIDNEQ(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNEQ(FieldTalkgroupID, v))
}

// TalkgroupIDIn applies the In predicate on the "talkgroup_id" field.
func TalkgroupIDIn(vs ...int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldIn(FieldTalkgroupID, vs...))
}

// TalkgroupIDNotIn applies the NotIn predicate on the "talkgroup_id" field.
func TalkgroupIDNotIn(vs ...int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNotIn(FieldTalkgroupID, vs...))
}

// TalkgroupIDGT applies the GT predicate on the "talkgroup_id" field.
func TalkgroupIDGT(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGT(FieldTalkgroupID, v))
}

// TalkgroupIDGTE applies the GTE predicate on the "talkgroup_id" field.
func TalkgroupIDGTE(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGTE(FieldTalkgroupID, v))
}

// TalkgroupIDLT applies the LT predicate on the "talkgroup_id" field.
func TalkgroupIDLT(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLT(FieldTalkgroupID, v))
}

// TalkgroupIDLTE applies the LTE predicate on the "talkgroup_id" field.
func TalkgroupIDLTE(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLTE(FieldTalkgroupID, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldContainsFold(FieldLabel, v))
}

// LedEQ applies the EQ predicate on the "led" field.
func LedEQ(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldLed, v))
}

// LedNEQ applies the NEQ predicate on the "led" field.
func LedNEQ(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNEQ(FieldLed, v))
}

// LedIn applies the In predicate on the "led" field.
func LedIn(vs ...string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldIn(FieldLed, vs...))
}

// LedNotIn applies the NotIn predicate on the "led" field.
func LedNotIn(vs ...string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNotIn(FieldLed, vs...))
}

// LedGT applies the GT predicate on the "led" field.
func LedGT(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGT(FieldLed, v))
}

// LedGTE applies the GTE predicate on the "led" field.
func LedGTE(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGTE(FieldLed, v))
}

// LedLT applies the LT predicate on the "led" field.
func LedLT(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLT(FieldLed, v))
}

// LedLTE applies the LTE predicate on the "led" field.
func LedLTE(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLTE(FieldLed, v))
}

// LedContains applies the Contains predicate on the "led" field.
func LedContains(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldContains(FieldLed, v))
}

// LedHasPrefix applies the HasPrefix predicate on the "led" field.
func LedHasPrefix(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldHasPrefix(FieldLed, v))
}

// LedHasSuffix applies the HasSuffix predicate on the "led" field.
func LedHasSuffix(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldHasSuffix(FieldLed, v))
}

// LedIsNil applies the IsNil predicate on the "led" field.
func LedIsNil() predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldIsNull(FieldLed))
}

// LedNotNil applies the NotNil predicate on the "led" field.
func LedNotNil() predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNotNull(FieldLed))
}

// LedEqualFold applies the EqualFold predicate on the "led" field.
func LedEqualFold(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEqualFold(FieldLed, v))
}

// LedContainsFold applies the ContainsFold predicate on the "led" field.
func LedContainsFold(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldContainsFold(FieldLed, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldContainsFold(FieldName, v))
}

// OrderEQ applies the EQ predicate on the "order" field.
func OrderEQ(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldOrder, v))
}

// OrderNEQ applies the NEQ predicate on the "order" field.
func OrderNEQ(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNEQ(FieldOrder, v))
}

// OrderIn applies the In predicate on the "order" field.
func OrderIn(vs ...int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldIn(FieldOrder, vs...))
}

// OrderNotIn applies the NotIn predicate on the "order" field.
func OrderNotIn(vs ...int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNotIn(FieldOrder, vs...))
}

// OrderGT applies the GT predicate on the "order" field.
func OrderGT(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGT(FieldOrder, v))
}

// OrderGTE applies the GTE predicate on the "order" field.
func OrderGTE(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGTE(FieldOrder, v))
}

// OrderLT applies the LT predicate on the "order" field.
func OrderLT(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLT(FieldOrder, v))
}

// OrderLTE applies the LTE predicate on the "order" field.
func OrderLTE(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLTE(FieldOrder, v))
}

// OrderIsNil applies the IsNil predicate on the "order" field.
func OrderIsNil() predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldIsNull(FieldOrder))
}

// OrderNotNil applies the NotNil predicate on the "order" field.
func OrderNotNil() predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNotNull(FieldOrder))
}

// SystemIDEQ applies the EQ predicate on the "system_id" field.
func SystemIDEQ(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldSystemID, v))
}

// SystemIDNEQ applies the NEQ predicate on the "system_id" field.
func SystemIDNEQ(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNEQ(FieldSystemID, v))
}

// SystemIDIn applies the In predicate on the "system_id" field.
func SystemIDIn(vs ...int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldIn(FieldSystemID, vs...))
}

// SystemIDNotIn applies the NotIn predicate on the "system_id" field.
func SystemIDNotIn(vs ...int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNotIn(FieldSystemID, vs...))
}

// SystemIDGT applies the GT predicate on the "system_id" field.
func SystemIDGT(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGT(FieldSystemID, v))
}

// SystemIDGTE applies the GTE predicate on the "system_id" field.
func SystemIDGTE(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGTE(FieldSystemID, v))
}

// SystemIDLT applies the LT predicate on the "system_id" field.
func SystemIDLT(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLT(FieldSystemID, v))
}

// SystemIDLTE applies the LTE predicate on the "system_id" field.
func SystemIDLTE(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLTE(FieldSystemID, v))
}

// TagIDEQ applies the EQ predicate on the "tag_id" field.
func TagIDEQ(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldEQ(FieldTagID, v))
}

// TagIDNEQ applies the NEQ predicate on the "tag_id" field.
func TagIDNEQ(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNEQ(FieldTagID, v))
}

// TagIDIn applies the In predicate on the "tag_id" field.
func TagIDIn(vs ...int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldIn(FieldTagID, vs...))
}

// TagIDNotIn applies the NotIn predicate on the "tag_id" field.
func TagIDNotIn(vs ...int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldNotIn(FieldTagID, vs...))
}

// TagIDGT applies the GT predicate on the "tag_id" field.
func TagIDGT(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGT(FieldTagID, v))
}

// TagIDGTE applies the GTE predicate on the "tag_id" field.
func TagIDGTE(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldGTE(FieldTagID, v))
}

// TagIDLT applies the LT predicate on the "tag_id" field.
func TagIDLT(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLT(FieldTagID, v))
}

// TagIDLTE applies the LTE predicate on the "tag_id" field.
func TagIDLTE(v int) predicate.Talkgroup {
	return predicate.Talkgroup(sql.FieldLTE(FieldTagID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Talkgroup) predicate.Talkgroup {
	return predicate.Talkgroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Talkgroup) predicate.Talkgroup {
	return predicate.Talkgroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Talkgroup) predicate.Talkgroup {
	return predicate.Talkgroup(sql.NotPredicates(p))
}
