name: Static Checks
on: pull_request

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go generate ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          skip-cache: true
          only-new-issues: true
